### ISSUE TITLE
Support remote SE via SRM

### ISSUE THREAD

**Issue by matz-e** [matz-e/lobster#101]
The master still relies heavily on direct/hadoop/chirp access to the SE.  We should be able to manage remote storage with SRM, too.

**Comment by matz-e** [comment]
Some notes on GFAL2:

```
export GFAL_CONFIG_DIR=/cvmfs/oasis.opensciencegrid.org/mis/osg-wn-client/3.2/3.2.22/el6-x86_64/etc/gfal2.d/
export GFAL_PLUGIN_DIR=/cvmfs/oasis.opensciencegrid.org/mis/osg-wn-client/3.2/3.2.22/el6-x86_64/usr/lib64/gfal2-plugins/
source /cvmfs/oasis.opensciencegrid.org/osg-software/osg-wn-client/3.2/current/el6-x86_64/setup.sh
```
Then
```
import gfal2
```
in python.

**Comment by klannon** [comment]
Is this a replacement for the SRM utilities?

**Comment by matz-e** [comment]
It's basically an abstraction, with SRM being one plugin.  I haven't found any python bindings for SRM so far, and I do not want to parse the SRM output by hand.  `gfal-copy` for example, can handle SRM URLs.

The [website](https://dmc.web.cern.ch/projects/gfal-2/home) has a list of protocols that are supported… and it is present in the same CVMFS repository as SRM.

**Comment by matz-e** [comment]
Expanding on this: [here](https://github.com/matz-e/lobster/commit/447724805dda8da269c983b14594c49b0d3a7a00) I've removed almost all dependencies on the chirp module (save for checking that a chirp server is running).

I think we should abstract this out into a `se/chirp.py` and `se/cms.py` module, where the latter uses xrootd for data streaming and SRM for stage-out and managing.  For merge job creation, this may be a little more involved, as we might incur a penalty for talking to a remote server for some operations.  This may lead to some operations being async or the whole merge job creation/checking being done in a separate process.

These SE modules then would have to be hooked up to the `fs` module to opaquely switch how we're dealing with the SE?  `fs` is currently used in the `core`, `job`, `cmssw/dataset`, `cmssw.job` modules.

**Comment by annawoodard** [comment]
Hi @matz-e. I think this all sounds good, but I think that the issues brought up during testing of #106 should be addressed first. I'll update there from the email thread.

**Comment by matz-e** [comment]
Progress!
