### ISSUE TITLE
Add option to receive core dumps

### ISSUE THREAD

**Issue by matz-e** [matz-e/lobster#104]
Sometimes, Lobster crashes without any error, and I suspect that WQ segfaults.  In these cases, it would be nice to have a core dump.  But `earth`'s `ulimit` is 0.

We can use [the first answer here](http://stackoverflow.com/questions/25475906/set-ulimit-c-from-outside-shell) to set the `ulimit` for core dumps higher as a configuration option for debugging.

**Comment by annawoodard** [comment]
+1 +1 +1 +1 +1 +1 +100000000000000000
