### ISSUE TITLE
mega-scale run

### ISSUE THREAD

**Issue by annawoodard** [matz-e/lobster#109]
Let's keep track of our preparations for the scale test here. Please add anything I've missed.

- [x] 0. investigate segfaults [@matz-e, @annawoodard, @khurtado]
- [x] 1. implement SRM stageout [@matz-e]
- [x] 2. test SRM stageout [@matz-e]
- [x] 3. test SRM stageout [@annawoodard]
- [x] 4. implement LHE splitting [@annawoodard]
- [x] 5. prep 'plan A' MC production [@annawoodard]
- [ ] 6. test 'plan A' MC production [@annawoodard]
- [x] 7. prep 'plan B' MC production [@matz-e]
- [ ] 8. test 'plan B' MC production [@matz-e]
- [x] 9. check dashboard reporting [@khurtado]
- [ ] <del>10. check bandwidth usage [@annawoodard]</del>
- [x] 11. decide on target job runtime [everyone]
- [ ] 12. <del> if necessary, transfer PU files to ND [@annawoodard] </del>
- [ ] 13. prep 'plan C' BEAN processing [@muell149]
- [x] 14. memory usage-- need to get this down as much as possible
- [x] 15. should we run with merging? [YES]

**Comment by klannon** [comment]
Just wanted to check on the status.  Have we had any test of any workflow at the scale of a few thousand simultaneous tasks?  We need to do something like this to test the squid readiness.

**Comment by annawoodard** [comment]
Sorry about the delay. Queue conditions are such that I have only gotten ~1,000 cores for the previous test (using chirp for stageout): http://www.crc.nd.edu/~awoodard/lobster/LHE_v13_merge_a_b_d_e_AOD_v1a_scale_test/

I'm currently observing 3x the overhead for non-dedicated vs dedicated resources. For future tests, I'm moving to 1-core workers to increase the squid load despite the queue conditions.

My first test with SRM stageout was unsuccessful; I'm currently investigating the error and will submit new workers shortly.

**Comment by annawoodard** [comment]
One critical issue that I'm also looking into: these AOD jobs are using more memory than the GEN jobs I've been running lately, about ~2-3GB/task. Can anyone confirm how much total memory we will have available? Running:

    condor_status -format "%-40s" Name -format "%f\n" Memory | awk '{sum+=$2} END {print sum}'

returns 17216644 MB, meaning that conservatively I will run out of memory at ~6,000 cores. But that does not include the backfilled cores, correct? I will ping Paul to confirm the actual value. In any case, I'm also preparing a GEN test run now as an alternative.

**Comment by annawoodard** [comment]
Updating with information from Paul:
> There is significant heterogeneity but most servers have either 1 or 2GB per core.  None have less than 1GB per core but Condor often accounts for instantaneous use and the OS will occupy some RAM so a 90% safety factor would be well advised.

Maybe we should consider a bimodal approach, here. One test doing productive physics (and being totally realistic, while memory-limited), and one more contrived test that we can hack to use less memory? @matz-e, how much memory do your jobs require? Ntuplizing jobs use less memory, but of course, then we're bandwidth limited.

**Comment by annawoodard** [comment]
Results from the second test are going here: http://www.crc.nd.edu/~awoodard/lobster/LHE_v13_merge_a_b_d_e_AOD_v1b/

It is not yet clear what is causing the worker disconnections. @matz-e, @khurtado, have you seen this in any of your recent runs? @btovar is helping me look into it now.

**Comment by klannon** [comment]
Did you figure this out?  The memory/core plot looks a little 
suspicious.  There are little spikes in most cases right as you have the 
big drops in workers.  Are you jobs blowing up their memory usage?

**Comment by annawoodard** [comment]
@btovar figured out that it is an issue with the fast abort on the cctools side. He asked me to test without fast abort to confirm, which I've done:
http://www.crc.nd.edu/~awoodard/lobster/LHE_v13_merge_a_b_d_e_AOD_v1b_no_fast_abort/

I think that confirms that the issue is related to fast abort. I move for us to plan to disable it for the scale test.

**Comment by annawoodard** [comment]
My last test segfaulted (about five minutes after I left the office and was offline for a few hours-- why does it always happen that way?). I suspect this is a cctools issue, related to what prompted @matz-e to open #104. I have moved this issue to the top of the to-do list. @pivie has seen something similar and opened cooperative-computing-lab/cctools#755. @pivie has recommended gdb for obtaining a trace:

    $ gdb python
    > run lobster process --foreground <lobster_config.yaml>
    … wait for segfault …
    > backtrace

I have started a new run, hoping to catch a segfault, but I'm not sure how long it will take. @matz-e and @khurtado, if either of you have the bandwidth, it would be good if you could try to leave a lobster process running tomorrow to try and catch one, too. If we catch one, we'll post it on the cctools issue, and try to support the cctools team however we can in order to get this identified.

**Comment by matz-e** [comment]
I'll push a branch for cores, too.

**Comment by annawoodard** [comment]
Notes:

> - [x] 0. investigate segfaults [@matz-e, @annawoodard, @khurtado]

@btovar has applied a hotfix for the segfault issue in the current version of ndcms-cctools-- I am having some issues with that version though (still not sure if it's on the cctools or lobster side), so for now I think we should plan to run with ndcms-cctools-backup and the scale_run_with_hacks branch, which has the cvmfs hack enabled. 

> - [x] 9. check dashboard reporting [@khurtado]

@khurtado has done this. We need to be careful to use lobster terminate to properly set the status in Dashboard.

> - [x] 10. check bandwidth usage [@annawoodard]

I haven't been able to do a careful test due to core availability, but we've convinced ourselves we don't need to worry about this.

> - [ x] 11. decide on target job runtime [everyone]

With @klannon and @matz-e we've decided on a target 1-2 hours.

> - [ ] 12. if necessary, transfer PU files to ND [@annawoodard]

Hasn't been done and probably (hopefully) not necessary, see item 10.

> - [ ] 14. memory usage-- need to get this down as much as possible

@matz-e has a GEN-SIM configuration that uses ~700 MB and Mike helped me get my big one down to 1.5 - 2 GB. I also have a GEN configuration that uses much less, but it processes so quickly that I'm worried about not having enough, so for the low-memory stage of the tests, I vote we start with @matz-e's configuration and switch to mine if we run into issues.

> - [ ] 15. should we run with merging?

@matz-e votes yes, let's do it unless there are objections.

**Comment by annawoodard** [comment]
I am closing this issue. Based on our experience with this test, I'd like to record a lesson learned here to apply for the next scale test:  <b> TESTING IS NOT USEFUL UNLESS YOU ARE TESTING THE CODE YOU WANT TO RUN. We need to integrate and freeze the code earlier-- at least a week or two before a big test like this, and only apply critical bugfixes afterwards.</b> We also need a backup of any external dependencies we have, so that if they change after testing has been performed, we can roll back to the tested version.
