### ISSUE TITLE
Following the installation instructions does not work.

### ISSUE THREAD

**Issue by annawoodard** [matz-e/lobster#119]
Easy_install is not able to setup dependencies correctly. In my last attempt, easy_install failed to install lobster because it could not find pyyaml, but independently installing pyyaml worked fine. Related: we officially support python 2.6, but newer CMSSW releases ship with python 2.7. There may be an issue installing hadoopy with python 2.7-- we should verify this, and try to converge on a recipe that works for both.

**Comment by klannon** [comment]
Yikes!  We will completely lose the ND user-base if you can't do an easy installation for Lobster.  It's easy to forget as developers, but most people aren't willing to manually futz with dependencies and versions (e.g. trial and error) just to get software working.  We need a recipe at least!

**Comment by annawoodard** [comment]
Allie is getting setup now, so I will look into this today.

**Comment by annawoodard** [comment]
I had a quick look at this earlier. As discussed on Slack, hadoopy does not seem to be maintained currently, so it would be best to move to something with better support (snakebite and pydoop seem like good alternatives.) I was able to install snakebite, but it did not work out of the box. I wasn't able to install pydoop with python 2.6 or 2.7. I'm reassigning this so that @matz-e can give finding a nicer solution a try. If we don't converge on something quickly, I propose we just add instructions to install hadoopy by hand, which works for me in both python versions:

    pip install --user -e git+https://github.com/bwhite/hadoopy#egg=hadoopy

**Comment by klannon** [comment]
I'm sending this back to @annawoodard with the idea that we shouldn't mess with finding a new hadoop interface at this point.  Just change the directions to instruct people to install hadoopy manually.  Once that's done, we can close this issue, I think.
