### ISSUE TITLE
Remove Dependence on Hadoopy

### ISSUE THREAD

**Issue by klannon** [matz-e/lobster#120]
Since it seems that Hadoopy isn't actively supported anymore, we shouldn't depend on it.  My preference is not to have Lobster mess with Hadoop directly, but rather rely on FUSE.  However, this has caused problems in the past.  Correctly solving this issue involves rethinking how things are structured, and deciding how important it is for us to support direct Hadoop access in python and if it's found to be crucial, what is the right package for accomplishing this.  Therefore, I'm putting it as a low-priority enhancement.  To be clear: One possible path to resolution is just to decide direct HDFS access isn't needed in Lobster.  We just need to do the proper cost vs benefits analysis, consider the appropriate long-term timescale.

**Comment by matz-e** [comment]
Will be addressed with 65106a17143853c9b85483f2c19c4ac3db38c7bd.

**Comment by matz-e** [comment]
(Testing at CERN works only w/o hadoop support)

**Comment by matz-e** [comment]
[Hadoopy actually just cooks with water and runs `hadoop fs` in the background](https://github.com/bwhite/hadoopy/blob/master/hadoopy/_hdfs.py).  We could do the same in a module on our own…
