### ISSUE TITLE
Improvements to file cleanup.

### ISSUE THREAD

**Issue by annawoodard** [matz-e/lobster#123]
We [currently](https://github.com/matz-e/lobster/blob/master/lobster/cmssw/job.py#L543) inform the user if we have failed to remove a bad file. We should make sure we are correctly differentiating between failures because the bad file doesn't exist, and failures because we couldn't remove it. We should keep better track of the latter failures, and at least prepare a summary of bad-files-which-couldn't-be-removed to display at the end of processing.

Of course, for published projects, this doesn't matter, but being able to quickly run over files in a directory without having to worry about duplicate processing is a big advantage of Lobster, IMO.

**Comment by matz-e** [comment]
Good catch!  I think you should also fold `IOError` into that clause, though.  If I'm not mistaken, that's what hadoopy had as an error code?

**Comment by annawoodard** [comment]
>>>> from lobster import fs
    >>>> fs.remove('/hadoop/spam')
    [...]
    IOError: Ran[hadoop fs -rmr /spam]: rmr: cannot remove /spam: No such file or directory.

    >>>> fs.remove('spam')
    [...]
    OSError: [Errno 2] No such file or directory: 'spam'

I think most IOErrors should be of the bad-file-doesn't-exist variety (which aren't a problem, since they don't cause duplicated events), in which case, it will just confuse the user if we report them. Now that I check it more carefully, it looks like the same goes for OSErrors (unfortunately, it'd be nice if the same problem returned the same error.) So it looks like instead of adding IOErrors to the clause, I think I should remove OSErrors. But maybe I'm missing something?

I have only seen a ValueError once, and it was definitely of the can't-remove-bad-file variety. Rather than reporting it, I just switched to catching and logging it. If it seems to happen a lot I'll open a separate issue to investigate further.

**Comment by matz-e** [comment]
Is this still relevant? I'd say that the `validate` command should take care of output files that Lobster could not remove. We could have the validation also be run automatically upon completion of a project… (and shove the output into the email sent out)

**Comment by annawoodard** [comment]
Sure, I opened running validation automatically in #532, closing this.
