### ISSUE TITLE
We should consider clarifying our nomenclature.

### ISSUE THREAD

**Issue by annawoodard** [matz-e/lobster#133]
We currently have some terms which overlap/conflict in meaning with WQ and HTCondor. This causes unnecessary difficulty when communicating with people who are not Lobster experts. It would be best if we could reduce that overlap. Here are are some possibilities:

**CURRENT**
**project:** group of tasks
**task (same name as WQ task, but different meaning):** group of jobits with a common set of input files (or a specified amount of simulation)
**job (corresponds to WQ task, same name as HTCondor job, but different meaning):** a group of jobits that are assigned to run on a single worker core
**jobit:** the smallest element into which the overall task can be divided and still be submitted as a self-contained task to a remote worker
**WQ task:** basically equivalent to our ‘job'
**HTCondor job:** The WQ worker wrapper we submit to condor

**PROPOSED**
**project:** group of batches
**batch:** group of jobits with a common set of input files (or a specified amount of simulation)
**jobit:** is the smallest element into which the overall batch can be divided and still be submitted as a self-contained task to a remote worker
**task (corresponds to WQ task):** a group of jobits that are assigned to run on a single worker core.
**HTCondor job:** The WQ worker wrapper we submit to condor

@matz-e has suggested to replace 'batch' above with 'workflow', which I support.

**Comment by annawoodard** [comment]
Note that I edited the previous comment's proposed jobit description.

**Comment by annawoodard** [comment]
Note that the current jobit description is cut-and-pasted directly from our paper. We use the word 'task' twice in *the same sentence* with two different meanings!

**Comment by klannon** [comment]
I'm actually completely fine with the proposal, with or without the batch->workflow replacement.  (I guess I have a slight preference for workflow.  This is different from what we discussed earlier because "taskit" is now "jobit," right?

Note: in English, "task" and "job" are synonyms, and so could be used interchangeably.  So, if we need more terminology, we can consult the Thesaurus:
http://www.thesaurus.com/browse/job

If we need another "job" term, I propose we next adopt "gig."

**Comment by btovar** [comment]
If job is going to refer to a Condor job, then I agree with @annawoodard that we should drop the term jobit. It is catchy, but without an enclosing job looks weird.

A lobster task could be divided into subtasks? tasklets? work units? crickets?

**Comment by annawoodard** [comment]
Oooh, I really like tasklets! It has a great advantage of sounding like what it is. But there is a drawback to changing the name jobits at this point, because there are some people outside  of the 'inner circle' who have been exposed to it. That change would be motivated by linguistic correctness (which is important), while the changes to the definitions of 'tasks' and 'jobs' are motivated by not overlapping with other definitions (which I would argue is more important).

I'm going to narrow the field down, please add more opetions if you want them to be considered, but can anyone with an opinion on this please vote, and let's wrap this up in the next day or so? Either is fine with me. @khurtado @klannon @matz-e @btovar 

[vote!](http://www.poll-maker.com/poll337118x76eB4769-13)

**Comment by khurtado** [comment]
I like and support the batch->workflow & jobit->tasklet terminology.

Best,
Kenyi
