### ISSUE TITLE
Report cores/task to dashboard

### ISSUE THREAD

**Issue by annawoodard** [matz-e/lobster#142]
For multicore tasks, we are not reporting the number of cores to the CMS dashboard (see 'running jobs' vs 'running job Cores' [here](http://dashb-cms-jobsmry.cern.ch/dashboard/request.py/dailysummary#button=jobstatus&sites%5B%5D=T3_US_NotreDame&sitesSort=3&start=2015-07-13&end=2015-07-13&timerange=daily&granularity=Hourly&generic=0&sortby=0&series=All), where I'm running ~1,000 tasks with 4 cores / task.) Note this is not multicore _workers_ but rather tasks for which we call task.specify_cores(x), where x is given in the user configuration as 'cores per job'.

**Comment by klannon** [comment]
What multicore application are you running?

**Comment by annawoodard** [comment]
Madgraph.

**Comment by klannon** [comment]
Is this something new, or have you always done it this way?  Just curious...

**Comment by annawoodard** [comment]
I've done it this way since adding the 'cores per job' option in Lobster, which allows us to run multicore applications. That was done in March (see fcde9b0).

**Comment by annawoodard** [comment]
See related info here: https://hypernews.cern.ch/HyperNews/CMS/get/wmDevelopment/702.html

**Comment by khurtado** [comment]
So, the idea would be to report the number in 'cores per job' from the worker node for all but the merge jobs?

**Comment by annawoodard** [comment]
Yes, although I'm not sure if there's a simple way to detect that on the worker-- maybe @btovar knows [1]? Otherwise, we could propagate it to the worker in the the parameters json file.

[1] To state the question more clearly: is there a way to detect inside a process running on a worker how many cores have been specified on the master side via task.specify_cores?

**Comment by btovar** [comment]
We have tested by exporting the CORES environment variable, but this has not been released. I can make it available to you if you need it.

**Comment by khurtado** [comment]
@btovar Sounds good to me!

**Comment by khurtado** [comment]
I made a branch to test these things... just adding the parameter to the parameters json file for now. No idea if this will work yet though :)

**Comment by klannon** [comment]
Whatever happened to this?  Now that I'm running lots of multicore tasks for MC production, it would be nice if the running cores reflected the actual core count and not just 1 core / task:

![jobnumbers_individual](https://cloud.githubusercontent.com/assets/5149849/12014281/3454281e-acf7-11e5-9ac7-07ea199be10e.png)

<img width="1095" alt="matrix10k" src="https://cloud.githubusercontent.com/assets/5149849/12014284/54ff9594-acf7-11e5-820e-977a39539ada.png">

(Images meant to show that we have up to 10k cores but aren't showing nearly that many tasks.  The jobs plot = the cores plot in dashboard.)
