### ISSUE TITLE
Merging multicore tasks introduces an inefficiency.

### ISSUE THREAD

**Issue by annawoodard** [matz-e/lobster#145]
@khurtado noticed that we're specifying the number of cores in core.py without checking what kind of job it is. This means that if `cores per job != 1` and merging is enabled, there is an inefficiency because the merge jobs do not use all of the cores. I don't know of a good way to deal with one master that has mixed requirements. I think for now it probably makes sense to just add a warning message to the user in these cases advising that multicore tasks + merging introduces this inefficiency and isn’t recommended, unless @btovar has an idea. There is always the hack that the user can process the data with merging disabled, then change `cores per job` and run the merge jobs.

**Comment by btovar** [comment]
Cores are defined per task, no per job. When creating the task you could say:

if merge_task: 
  t.specify_cores(1)
else:
 t.specify_cores(4)

**Comment by annawoodard** [comment]
Sweet! I don't know why I was inventing a restriction that wasn't there. I guess the fact that specify_cores() is a method of Task() should have given me a hint. Anyways, that's good news, we'll implement it. Thanks @btovar!
