### ISSUE TITLE
Enable log read access for groups

### ISSUE THREAD

**Issue by annawoodard** [matz-e/lobster#149]
Currently only the user has read access to the executable log. It would be convenient to give read access for the user's groups for debugging.

**Comment by matz-e** [comment]
+1

Or even inherit the umask of the parent directory?  If that directory is world-readable, I think the logs should be, too.

**Comment by annawoodard** [comment]
+1 for inheriting from the patent directory!

**Comment by matz-e** [comment]
See the [work queue code](https://github.com/cooperative-computing-lab/cctools/blob/master/work_queue/src/work_queue.c#L824), which hardcodes the umask!  Should we work around this?

**Comment by matz-e** [comment]
This does not show up in `cctools-023-0812dc8b-cvmfs-40cf5bba` anymore, which has default permissions of `0777`.  Thus closing this.
