### ISSUE TITLE
Add handling for task.result

### ISSUE THREAD

**Issue by annawoodard** [matz-e/lobster#150]
We need to add handling for [task.result](http://ccl.cse.nd.edu/software/manuals/api/html/classwork__queue_1_1Task.html#a96170c2cb7416e66882d83c1b2d25b18); in particular, this is how WQ communicates to us if a worker has exceeded their disk usage.

**Comment by matz-e** [comment]
Duplicate of #80 ;)

**Comment by annawoodard** [comment]
Ah, sorry I missed that.
