### ISSUE TITLE
Improve Handling of Problem Files

### ISSUE THREAD

**Issue by klannon** [matz-e/lobster#155]
Right now, if there are a few bad input files (e.g. corrupted at a T2 site), Lobster tries forever on those files.  It would be nice to tell Lobster to give up after a certain number of failures and move on to finish the rest of the jobs.  Here's what would be needed basically to implement the minimal version:

From @matz-e on [Slack](https://ndlobster.slack.com/messages/lobster-debug/):
>to account for skipped jobits, jobits_done in jobit.py would have take into account the jobits skipped from the files table (where appropriate.) line 213 is where the files would have to be actually skipped during job creation.  Then we would probably like to include skipped jobits in the plotting info page.

There are a number of additional features which should be included to make a complete implementation:
From @annawoodard on [Slack](https://ndlobster.slack.com/messages/lobster-debug/):
>And you'll need to add a flag in the lobster configuration that the user can use to set the number of retries before skipping a file 

and

>You should also probably add a snippet in cmssw/data/job.py which ensures that skipBadFiles is enabled 

From me:
* I think we also need some way for the user to specify whether skipping files is OK.  (E.g. for data we might not want to skip files.  
* Ideally, there'd also be a way to come back later and say please retry those skipped files again without expecting the user to hack the DB directly.

**Comment by annawoodard** [comment]
> I think we also need some way for the user to specify whether skipping files is OK. (E.g. for data we might not want to skip files.

This convention has always seemed a little unintuitive to me, but we could always have `number of retries = -1` mean 'retry forever' and `number of retries = 0` mean 'do not skip files'.

> Ideally, there'd also be a way to come back later and say please retry those skipped files again without expecting the user to hack the DB directly.

Since we don't have more sophisticated validation in place yet that compares lobster configurations between successive restarts of the same project, depending on your implementation, changing the retries flag in the lobster configuration and restarting the project would probably have this effect. We should put something less hacky in though (and eventually do better validation, we have an issue for that somewhere.)

**Comment by klannon** [comment]
OK, then I'll use your suggested retry interpretation to address the first point and consider the second one "implemented already" until we reach a more mature state with restarting projects.  Thanks!

**Comment by klannon** [comment]
OK, here's my workplan then (because I spent the whole day today understanding how this code works and now I need to go see to other things:
1.  In jobits.py, when it gets out the list of files that it's going to try, if `skipped` is above a configurable threshold, then don't include that file.  I think I can just go ahead and do this in the sql query since in this part of the code, I see no reason to keep a record of whose being skipped.  Once a file goes above the skip threshold, it will just disappear from the list of files used to generate jobs.
2.  I can make this configurable right away because you guys are smart and already passed access to the full configuration around everywhere.  So I don't need to figure out how to hook a new config variable up to this part of the code, because the hooks are already there.  Thanks!
3.  If we're skipping files, we'd better let the user know this.  It seems to me like the right thing to do is to add a column to the datasets table for skipped events.  So I should update plotting.py and associated files.  It would probably maybe also make sense to add the list of skipped files in a table somewhere on that page.  Suggestions welcomed!
4.  While I'm in there, maybe add some comments to jobits.py to shorten the learning curve for the next person through.

I think that would accomplish the minimum acceptable implementation of this feature.  I probably won't get to the actual coding until Monday...
