### ISSUE TITLE
Change cache definition behavior

### ISSUE THREAD

**Issue by matz-e** [matz-e/lobster#157]
Write the cache file with a timestamp immediately after setting the cold cache flag, and have all subsequent job check that their time is greater than the saved one to be hot.

**Comment by annawoodard** [comment]
Also: move the setting-of-the-flag to earlier? I think that technically the right cutoff would be after the cmssw job setup, but the only handle we have on that time is after-the-fact.

**Comment by matz-e** [comment]
If we are setting an earlier time, I don't think that will hurt anything.  By construction, only the first done job will set a time… although I guess if, e.g., the second finished job has an earlier time of the 1st event processing, it could update the file.

**Comment by matz-e** [comment]
Single worker with 1 concurrent task looks as expected: http://www.crc.nd.edu/~mwolf3/lobster/cache_single/

**Comment by matz-e** [comment]
And single worker with 16 concurrent tasks: http://www.crc.nd.edu/~mwolf3/lobster/cache_more/

**Comment by matz-e** [comment]
OK.  I'm noticing two things:

1. The binning is unfortunate, as it is calculated separately for hot and cold cached jobs.
2. Failed jobs are not included when splitting by cache type.  This may potentially be confusing when looking at the timing plots.
3. Some hot cache jobs take a long time to setup (15 min in one case, checked via the db / `report.json`)

**Comment by matz-e** [comment]
Also note that [these plots](http://www.crc.nd.edu/~mwolf3/lobster/cache_more/) would look the same with a changed definition of the hot cache cutoff time.  The one outlier below at >45 minutes started when the first cold cache job returned!

![](http://www.crc.nd.edu/~mwolf3/lobster/cache_more/good-overhead-hist.png)

**Comment by matz-e** [comment]
`<monologue>`
Maybe part of this is an artifact of my small processing time?  I'll restart with longer jobs…
`</monologue>`

**Comment by annawoodard** [comment]
Hmm, I think that the changes you made to our definition of hot/cold are definitely the way to go, but we have two issues here-- the definition of hot/cold was not quite right, and the behavior of hot/cold is not completely understood. I think we've solved the former but not the latter, correct?

**Comment by matz-e** [comment]
Yes, it is not completely understood.  I'd suggest that I could run with a varying worker size in concurrent tasks and see when behavior differs from the single concurrent task state?  I'd maybe have the suspicion that too many concurrent cache accesses may slow the release setup down?

**Comment by annawoodard** [comment]
Seems plausible. But whatever it is, it is new, because after the first cache fix a long time ago, we've seen mostly expected behavior (we even have a plot of overhead vs workers / cache in the paper, I think.)
