### ISSUE TITLE
Handle file duplicates for new projects

### ISSUE THREAD

**Issue by annawoodard** [matz-e/lobster#162]
Despite various attempts we've made at safeguarding against this, if the user restarts a project hastily, there may be leftover files from previous attempts hanging around in the stageout directory. @batrick pointed out to me that I was having job failures because Chirp would not overwrite an existing file (SRM may act the same, I haven't verified this). This results in duplicated processing because those jobits are resubmitted until they land on a non-clobbering job id. I believe the simplest way to be absolutely sure to avoid this is to require that the stageout directory be empty when starting a project for the first time (I think our safeguards are working pretty well for project restarts). I realize this reduces our flexibility somewhat in the case someone wants to use the same directory for different projects, but I think that's crazy user behavior and we shouldn't support it.

**Comment by klannon** [comment]
+1 for not bending over backwards to support crazy user behavior. There 
are plenty of times in other tools where you're told things like "I 
won't do this because I expect to have A and you have B instead.  Fix it 
and I'll reconsider..."

**Comment by annawoodard** [comment]
This is easy to implement-- I'll wait until tomorrow to see if @matz-e wants to weigh in, then do so if there aren't any objections.
