### ISSUE TITLE
Stageout directory permissions

### ISSUE THREAD

**Issue by annawoodard** [matz-e/lobster#167]
The `lcg-cp` command will fail if `osgusers` does not have write-access to the stageout directory. We need to make sure that the permissions are set correctly when we create the stageout directory (possibly only if SRM is in `outputs`?)

It is not clear to me if the group that needs write-access is always `osgusers`, does anyone know?

```
/cvmfs/oasis.opensciencegrid.org/mis/osg-wn-client/3.2/3.2.25/el6-x86_64/usr/bin/lcg-cp -b -v -D srmv2 file://afs/crc.nd.edu/user/a/awoodard/foobar srm://ndcms.crc.nd.edu:8443/srm/v2/server?SFN=/hadoop/store/user/awoodard/bad/spam
file:/afs/crc.nd.edu/user/a/awoodard/foobar: zero number of replicas
lcg_cp: Invalid argument

/cvmfs/oasis.opensciencegrid.org/mis/osg-wn-client/3.2/3.2.25/el6-x86_64/usr/bin/lcg-cp -b -v -D srmv2 file://afs/crc.nd.edu/user/a/awoodard/foobar srm://ndcms.crc.nd.edu:8443/srm/v2/server?SFN=/hadoop/store/user/awoodard/spam
Transfer took 1000 ms

[earth] ~/lobster/examples >ls -lad /hadoop/store/user/awoodard /hadoop/store/user/awoodard/bad
drwxrwxrwx 103 awoodard osgusers 4096 Aug  3 17:00 /hadoop/store/user/awoodard
drwx--x---   2 awoodard osgusers 4096 Aug  3 16:58 /hadoop/store/user/awoodard/bad
```

**Comment by matz-e** [comment]
Hm… Is this another case where we don't inherit permissions from the parent directory?  It seemed to me that using `lcg-cp` without a pre-existing directory created it.

**Comment by matz-e** [comment]
Apparently directories like to be created in mode `0755` by local access and hadoopy.  We need to create them with at least `0775`, I think…

**Comment by matz-e** [comment]
FYI, hadoop does not seem to provide a way to read the permissions of a file?  This will make a custom `makedirs` implementation a lot harder.

**Comment by matz-e** [comment]
Actually, `ls -d` gives permissions…

**Comment by matz-e** [comment]
Status update: I think this is most relevant to local access methods, that are potentially going to be skipped on the (opportunistic) worker.  Setting permissions for SRM is a major pain, and Chirp is currently broken, so I'll mark this as fixed as soon as `hdfs` and `file` paths work.

**Comment by annawoodard** [comment]
> I'll mark this as fixed as soon as hdfs and file paths work.

:thumbsup:
