### ISSUE TITLE
Hard-Coded CRAB Version

### ISSUE THREAD

**Issue by klannon** [matz-e/lobster#175]
This looks like a bad thing to me, but I'm not really sure why it's there and I'm trying to track something else so I'm just going to post an issue for it and move on:

https://github.com/matz-e/lobster/blob/master/lobster/cmssw/data/job.py#L20

Why is there a specific CRAB version hard-coded here?  If a CRAB version is needed, we should be sending it with the job parameters, I think.

If I'm just confused, feel free to say so and close the issue...

**Comment by khurtado** [comment]
It is not only in data/job.py. It is also hardcoded in merge_reports.py, publish.py and dataset.py.  Besides that, we are using 2 different CRAB versions: 2_10_5 in some, and 2_10_2_patch2 in others:

https://github.com/matz-e/lobster/blob/fe78abcdab1b25ab85aba7a2d45b3d3f1be3e6f8/lobster/cmssw/data/merge_reports.py#L4
https://github.com/matz-e/lobster/blob/fe78abcdab1b25ab85aba7a2d45b3d3f1be3e6f8/lobster/cmssw/publish.py#L19
https://github.com/matz-e/lobster/blob/1190fc4007dbd59f3456a7268c746ae5b215b06e/lobster/cmssw/dataset.py#L7

Some other files like dash.py do not include any specific version of CRAB but it needs it, so it uses whatever the user has setup in the environment. That means we can end up using 3 different versions of CRAB between master and workers.

Also, I don't understand the include in publish.py. Lines 14-18 import things from ProdCommon and RestClient...
https://github.com/matz-e/lobster/blob/master/lobster/cmssw/publish.py#L14-L18

Aren't they coming from CRAB already? Then, why do we need to hardcode a specific version of CRAB before importing dbs.apis.dbsClient that comes from dbs3client?

Note RestClient  (which is imported before including  CRAB_2_10_2_patch2/dbs3client) also comes from the CRAB dbs3client external directory, so unless the lobster user has CRAB_2_10_2_patch2 setup, we are using 2 different dbs3clients directories. One for RestClient and another for dbs.

>>> import RestClient
>>> RestClient.__file__
'/cvmfs/cms.cern.ch/crab/CRAB_2_11_1_patch1/external/dbs3client/RestClient/__init__.py'

**Comment by matz-e** [comment]
This is a fairly hackish way to get dependencies, which will break at some point, so I guess we should fix it.  One problem is that I've not encountered some of the dependencies in a reliable format.  I.e. how are we supposed to obtain the source to the `dbs3client`?  Maybe I haven't looked enough…

The last import stems probably from the previous dependencies already being in the environment paths after a `cmsenv`, whereas the `dbs3client` is not.

**Comment by matz-e** [comment]
I'm working on getting rid of this.  Requires us to pull in our own version of DBS (I think I've got that covered), WMCore (WIP), and rewrite a wee bit of the actual CRAB2 support bits (which may disappear at some point in the future.)

On the upside, this should work without CVMFS, then, in case anyone still wants to experience installing CMSSW manually.
