### ISSUE TITLE
Lobster Only Supports EDM Outputs from CMS Jobs

### ISSUE THREAD

**Issue by klannon** [matz-e/lobster#176]
So, I was trying to adapt the 13 TeV workflow to Lobster and I started hitting a problem.  Eventually, I tracked it down to the fact that the output from these jobs are simple ROOT trees, but Lobster assumes that any ROOT output is EDM format.  This manifests in a couple of ways:

https://github.com/matz-e/lobster/blob/master/lobster/cmssw/data/job.py#L503

The function `get_bare_size()` measures the size of the `Events` tree and throws an exception if it's not there.  This is somewhat alleviated by 

https://github.com/matz-e/lobster/blob/master/lobster/cmssw/data/job.py#L333

which catches the exception and uses the file size instead of the "bare size."

The bigger problem is that merge jobs are constructed assuming EDM output, i.e. they use cmsRun.

I'm going to start working to address this.  For the first issue, I think I'll just improve the log messages slightly so that it's clear that it does record the file size even if the `Events` tree is not present.  For the second issue, I'm thinking of making an option to specify that you want to use `hadd` instead of `cmsRun` to merge files.  This will take a little bit of work, however.  Suggestions are welcomed...

**Comment by matz-e** [comment]
I have the same issue.  See #121.

**Comment by matz-e** [comment]
I think we can close both issues with 1c0da73867940d4e98d4c7befdafc725b718840b.
