### ISSUE TITLE
Skip Problematic Jobs or Jobits and Move on to Merging

### ISSUE THREAD

**Issue by klannon** [matz-e/lobster#186]
This is a critical feature for day-to-day usability:  If there is some piece of a dataset that cannot be processed (i.e. a corrupted file which causes your job to crash).  There needs to be a way either to tell Lobster to skip that piece, or for Lobster to figure out automatically that it's crashed the same way many times on a particular piece of work and shouldn't keep trying any more.

I think in this case, since users don't generally interact with specific jobs in Lobster, Lobster should decide when it's going to skip something, rather than the user trying to blacklist individual jobits manually.  (Although it might be handy to be able to blacklist specific input files...)  So, I think it would be nice if we could have a retry threshold, where if a given jobit has failed too many times, Lobster marks it as skipped and moves on.

In my ideal implementation, it would be that when a jobit reaches a given number of failures (e.g. non-zero return codes, eviction of course shouldn't count), Lobster tries the jobit one last time, but in a job all by itself.  This allows Lobster to process jobits who were only failing because they were consistently being grouped with one bad jobit.  (This certainly happens when there are so few jobits left that the same ones keep getting put together into one job.)  If the jobit fails after that, then it gets marked as skipped, and lobster moves on--merging all non-skipped job output and concluding its task.

There needs also to be a way for users to clear the skipped flags and let lobster try to finish the jobs that it previously skipped.

Is this feasible?  Suggestions on how to achieve it?  Better ideas?

**Comment by matz-e** [comment]
Do you have an example file/config?  I would think that we could enable skipping files by default, if we don't do so already.  If that solves one half, tracking skipped files should complete this.

OTOH, if some event crashes `cmsRun` I'd normally refer that back to the user to safeguard against.

**Comment by klannon** [comment]
Can you remind me what the config flag is for skipping bad input files.  
I thought I'd already enabled that because of a problem in the past, but 
I can't remember what to look for.  I agree that we should probably 
force that to be true, unless the user overrides it.

We might want to think about this as two interrelated problems:
   - What to do with persistent errors?  Currently we retry forever. 
There needs to be some way, either automated or manual, to tell Lobster, 
"Hey, that's close enough.  Let's finish merging and close this project out.
   - How to keep an error tied to one particular file, lumi, event, from 
keeping you from processing the others.  For this one, I think it 
definitely should be automated.  I'm personally really in favor of 
quarantining repeatedly failing jobits to their own job so that they 
can't block processing of other jobits.

What do you think?

**Comment by matz-e** [comment]
This is the similar to #155, I think.  Which we also have not implemented yet.  We could at the same time at a failure count to the file table, so that files that occur repeatedly in either failed jobs or are skipped are not considered anymore?

**Comment by matz-e** [comment]
One concern about the performance of our jobit selection (especially w.r.t. error checking for split lumi sections):  what would you think about doing this on a file level first, @klannon ?  I.e. we single out files in failed jobs, kind of like skipped files, and once we have reached the threshold, we can treat the jobits in them differently?

**Comment by klannon** [comment]
So, I've been thinking about this and I'm convinced that restricting this to tracking problems at the file level might be unwise.  However, my thought process might be flawed (I'm not sure I've fully wrapped my mind around how Lobster tracks things), so please correct my logic where necessary.

My main concern is that no everything that might persistently fail falls into the model of processing files.  For example, if you are trying to generate MC, and there is a particular random sequence that causes one jobit to fail repeatedly, it would be nice to skip that jobit and go on.  (OK, maybe you're thinking that we're not using reproducible seeds so this can't be a problem, but hopefully we'll be able to do this some day.)

My simple-minded view of how to implement this threshold is just to add a field to the jobits table that counts the number of times the jobit has been included in the construction of a job.  Every time you go to put the jobit in a job, you check the counter.  If the value is below the tries threshold, you proceed normally also incrementing the counter by one.  If the value is at the threshold, perhaps you do the try one more time but put this jobit in its own job approach.  If the counter is past the threshold, you skip this jobit and move on to another job.

What do you think of this approach?  Is it still too hard on the DB?

**Comment by matz-e** [comment]
Reviewing it, I think the cost shouldn't be too high, especially with an implementation how you describe it.

**Comment by klannon** [comment]
OK, then we just have to figure out how to work on this.  I'd be happy to take a shot at it, but I really can only devote part of Thurs and/or Friday per week.  Do you think doing this would require extensive modifications?  Any tips or suggestions?  Or would you just prefer to take care of it yourself?

**Comment by matz-e** [comment]
It doesn't require that many modifications, but touches a few places, including the logic of being done.  I think I could get the actual code modifications done in 1-2 hours, testing would consume most of the time.  I think we need to add a `failed` column to the jobits tables, and a `jobits_failed` column to the dataset table.  The latter would have to be updated [here](https://github.com/matz-e/lobster/blob/master/lobster/cmssw/jobit.py#L421), where we calculate how many jobits we have done.  Then all queries to determine the "doneness" need to be modified, as in [here](https://github.com/matz-e/lobster/blob/master/lobster/cmssw/jobit.py#L464), where `jobits_done + jobits_failed = jobits` would be more correct.  Similar changes are required for the [job creation](https://github.com/matz-e/lobster/blob/master/lobster/cmssw/jobit.py#L204).

**Comment by matz-e** [comment]
Oh, and since the database format would be changed, the [lobster version should be increased](https://github.com/matz-e/lobster/blob/master/setup.py#L7).  I'll have to add that to the contributing documentation, still.
