### ISSUE TITLE
Fix SE nosetests

### ISSUE THREAD

**Issue by annawoodard** [matz-e/lobster#191]
Currently `test_se.TestSRM` and `test_se.TestSRMPermissions` are failing. I don't believe there is a simple way to fix `test_se.TestSRMPermissions` because `gfal-mkdir` doesn't support setting the mode. We could use `srm-permission-set`, but I don't think it's worth the added complication/dependency. I think that since we're unlikely to be using the SRM backend master-side, we should just remove this test until we actually have any problems with this limitation (note we still need to fix `test_se.TestSRM`).

**Comment by matz-e** [comment]
For the record, I have used the SRM backend on the master side to use the CERN T2 to stage out.  I've also staged out to the ND T3 with a master running at CERN.  I actually don't mind the test failing, but we could comment the permissions one out…

**Comment by annawoodard** [comment]
Good point. But we still need a40dd31-- that's just a bug, not a limitation.

**Comment by matz-e** [comment]
Agreed.
