### ISSUE TITLE
Allow command arguments

### ISSUE THREAD

**Issue by annawoodard** [matz-e/lobster#197]
This configuration used to be allowed:
```
tasks:
    - {label: 'ttH', 'cmd': 'lhe.py --cores 4'}
```

but now fails because we've switched to not splitting the command before passing it to subprocess [here](https://github.com/matz-e/lobster/blob/master/lobster/cmssw/data/job.py#L638). We should allow for commands of the form `lhe.py --cores 4`.

**Comment by matz-e** [comment]
Can you do `['lhe.py', '--cores', '4']`.

**Comment by annawoodard** [comment]
I think it's clearer to be able to do either.

**Comment by annawoodard** [comment]
I'd be happy to add a catch in case it's already a list.

**Comment by matz-e** [comment]
Yes, but for splitting command lines, it's best to use [shlex](https://docs.python.org/2/library/shlex.html#shlex.split) to properly parse strings…

**Comment by annawoodard** [comment]
Is 00a331f what you had in mind?

**Comment by matz-e** [comment]
Exactly!
