### ISSUE TITLE
Custom commands do not get input files passed

### ISSUE THREAD

**Issue by matz-e** [matz-e/lobster#207]
We should append the list of input files to the custom command, otherwise this seems somewhat pointless?  Currently, this is only done for merge jobs.  Thoughts/comments, @annawoodard?

**Comment by annawoodard** [comment]
Yes, I agree! I've been parsing it out of parameters.json, which is clearly not the user friendly solution :).

**Comment by matz-e** [comment]
As far as I remember, we had a private conversation about this, where we found that we could have the following specification:
```
task:
  - label: foo
    cmd: "cat {files}|grep some_random_string>output"
```

And I think @annawoodard also proposed that we could apply this to `cmRun`:
```
task:
  - label: MyMessyTTH
    cmd: "cmsRun ntuplize.py"
    dataset: "/ttH*/*/MINIAOD"
```
Here we could condense three parameters into one: `cmd`, `pset`, and `parameters`.  For CMS jobs, we can split the command via `shlex` IIRC, and then remove a maybe already present `-j`, add our own for the job report, and extract the parameter set name, and add it to the inputs. Input files can then be used in the command, as long as the worker does:
```
cmd.format(files=map(pipes.quote, input_files))
```
and we execute `cmd` as a shell string.
