### ISSUE TITLE
Add summary of which hosts errors occurred on to plotting page

### ISSUE THREAD

**Issue by annawoodard** [matz-e/lobster#208]
As pointed out by @klannon, it is useful to look at which hosts a given error occurred on. We already have the information available to do this easily by error code (which isn't as powerful as grepping for specific messages, but it's worth trying the simpler implementation first). I think this would fit well into the log file table (see below). Maybe we could make the number in the 'occurrences' a link that would lead to a sorted unique list of hostnames where a job ran returning the given exit code, like:
```
     24 q16copt060.crc.nd.edu
     20 q16copt058.crc.nd.edu
      8 q16copt117.crc.nd.edu
```
Or alternatively, a column could expand? I'd say we could make the number hoverable except I that might make it hard to copy and paste, which would be useful.

![screen shot 2015-09-25 at 11 08 40 am](https://cloud.githubusercontent.com/assets/5114833/10104120/d3763976-6375-11e5-92b0-f3c8e0c17e75.png)

**Comment by klannon** [comment]
I agree that this would be useful, and I'd vote for making the implementation as simple as possible (e.g. a link or expandable list, whichever is easier and just based on exit codes).  If I understand correctly, if we were using ELK for this instead, we'd be able to, on the fly, define plots like "show me a histogram of all the host names for jobs whose executable logs had this message in them" or "show me the xrootd remote read site for all jobs that failed with this message on these hosts" or "make a table of error codes vs input data file names," etc.  I think we'll never manage to catch all of the cases with static monitoring plots, so we should just focus on the most useful ones (like your suggestion) and keep in the back of our head that something like ELK is probably required to handle the next level of usefulness.

**Comment by matz-e** [comment]
You have me now for ELK… I just started a server on earth, and it seems pretty easy to set up and use (should hook easily into lobster.) Haven't looked at the rest, but if they provide default reports, we could just port the current plotting over to a default report.  Otherwise, I agree that our endless querying/analysis abilities far exceed our capabilities to extend the plotting page.  So KISS it should be for now?
