### ISSUE TITLE
Kill jobs after yet another grace period.

### ISSUE THREAD

**Issue by matz-e** [matz-e/lobster#217]
We currently can limit data processing by having CMSSW quit after a certain time.  Now if data is accessed via XrootD and the server has issues, CMSSW will not quit, since it only checks whether to do so when a lumi section ends.  Hence we should kill the job if it exceeds maybe twice the alloted time (including original grace period), preferably via WQ mechanisms?  @annawoodard, @btovar is this possible with resource monitoring in WQ?

**Comment by annawoodard** [comment]
Sorry I'm slow, I'm not following how this is different from fast abort though?

**Comment by matz-e** [comment]
Fast abort takes the average of all job runtimes and then applies a multiplication factor to kill outliers.  This would be saying (roughly) "we tell CMSSW to quit after 30 minutes, WQ should kill the job after 60 minutes" - no matter what the average job runtime is.  Basically: Fast abort for when we don't know how long we are running for, this for when we do know how long we run at the most.

**Comment by annawoodard** [comment]
Thanks for the clarification, that makes sense.

**Comment by matz-e** [comment]
Fixed in 2e714e697646a1934bdb3a09376d15bc4b16a3b2.
