### ISSUE TITLE
Fix JobSummary pie chart

### ISSUE THREAD

**Issue by annawoodard** [matz-e/lobster#223]
The JobSummary pie chart is a little misleading because the 'eviction' slice is defined by `task.total_cmd_execution_time - task.cmd_execution_time`,  which should include time lost when tasks are internally resubmitted by WQ for idling out, etc.

**Comment by annawoodard** [comment]
It would be nice to have the time lost to internal resubmissions split by cause (eviction, idling out, etc), but I'm not sure it's high enough priority to request from the cctools folks?

**Comment by matz-e** [comment]
@annawoodard can we close this with the changes you and Ben added a while ago, a.k.a., the "exhausted" slice in the pie?

**Comment by annawoodard** [comment]
Sure thing. Sorry I missed closing this issue...

**Comment by matz-e** [comment]
No worries. Just wanted to make sure it's really fixed before closing it myself…
