### ISSUE TITLE
Remove doubled markers in plotting legends

### ISSUE THREAD

**Issue by matz-e** [matz-e/lobster#232]
See title…

**Comment by annawoodard** [comment]
Which markers are doubled?

**Comment by matz-e** [comment]
The one in profile plots - at least for me.  I always see two dots with arrow bars in the profile plot legends.

**Comment by annawoodard** [comment]
Ah! I see what you mean now. It's strange that matplotlib defaults that way. I've fixed this before in private plots, I'll pull it up.
