### ISSUE TITLE
Fix plot axes label units

### ISSUE THREAD

**Issue by matz-e** [matz-e/lobster#243]
We use `(m)` for the time plots, but `[MB]` for the memory/footprint plots.  Third option: `foo / unit`.

**Comment by annawoodard** [comment]
I vote brackets. Slashes are confusing because they usually mean division.

**Comment by matz-e** [comment]
In general, I've actually come to like the division (actually dividing the quantity on the axis to get unit-less), since it's visually less cluttered.  But if some y-axis have the bin width shown with a `/` as a separator, see #244, I agree that brackets are better.

**Comment by annawoodard** [comment]
Now that I think about it, brackets should be used for dimensions, so parentheses are better for units. So all the [MB] should go to (MB).

**Comment by matz-e** [comment]
Hm… that made me Google it, and I found [this](http://physics.nist.gov/Pubs/SP811/sec07.html):
> 2) The ordinate of a graph is labeled T/(10^3 K), where T is thermodynamic temperature and K is the unit symbol for kelvin, and has scale marks at 0, 1, 2, 3, 4, and 5. If the ordinate value of a point on a curve in the graph is estimated to be 3.2, the corresponding temperature is T / (10^3 K) = 3.2 or T = 3200 K. Notice the lack of ambiguity in this form of labeling compared with “Temperature (10^3 K).”
I that doesn't change your mind, parentheses they shall be at least.

**Comment by annawoodard** [comment]
Yeah, you are right. Sorry about the noise.

**Comment by matz-e** [comment]
No, I'm sorry for being a stick in the mud here.  Although it's nice to have that reference from NIST / some official authority.
