### ISSUE TITLE
Installation Problem with VirtualEnv: Dependencies

### ISSUE THREAD

**Issue by klannon** [matz-e/lobster#256]
Maybe it's just my concept of how Lobster installation should work, but I'm still having problems with dependencies.  I thought the point of moving to `virtualenv` was to decouple Lobster from CMSSW.  If this is the case, then I think there is still at least one missing dependency: `matplotlib`.  The only way I was able to successfully install and run Lobster without setting up CMSSW was as follows:

1.  Do `module load python` to pick up Python 2.7.8 + a bunch of useful packages (`numpy`, `scipy`, `matplotlib`, etc.)
2.  Do the `virtualenv` installation instructions from the README.
3.  Remember to activate a second time after Lobster is installed to get it in your path.  I'm not sure if this is strictly necessary.  A `rehash` might have done the trick.

Doing this allowed me to run Lobster without doing `cmsenv` first.  (Well, there were a couple of other small fixes required which I'll detail in separate issues.)

While I have your attention, for an installation from a local git repository, do you have to do `pip install . --upgrade` whenever you want to install local changes (e.g. when you edit the source)?  That seemed to be the only way I could get it to pick up my changes, but maybe I'm missing something.

**Comment by matz-e** [comment]
Actually, the point was to protect CMS workflows from Lobster dependencies, not the other way around. I think it would be desirable to be completely independent from CMSSW, but then that will be a rather strict dependency? Currently, RH6 ships only python 2.6, and I think that some of our dependencies may not support this much longer (`python-daemon`, e.g., received an update without any previous version being accessible anymore). We're lucky to be able to source newer python versions via the CRC, and I think CERN may have a similar setup.

As for `matplotlib`, I took that out while working with Geoff, as it breaks the install procedure. CMSSW apparently has `matplotlib` installed in a way that pip does not recognize it, and of course we're missing the right ingredients to compile `matplotlib` when sourcing the CMS environment.

**Comment by klannon** [comment]
OK fair enough.  Then I would suggest the following for consideration by the experts (i.e. @matz-e and @annawoodard):

1.  If Lobster is intended to be installed on top of CMSSW, I would suggest that it be made very clear when `cmsenv` should be done during the installation.  I've had issues in the past (or at least, I got confused and thought I had issues) because I would do `cmsenv` either too soon or too late and it would cause issues with my local `pip` or now, I think `virtualenv`.  I think having very clear guidance would be useful.  (If it's already there, and I'm just missing it because I'm blind, then you're best course of action is to claim to have added it just now in response to my comment and to try to make me feel guilty for asking you to work over the holidays.  :smile: ).

2.  We should keep some notes somewhere (would this be a new .md somewhere in the repo) of recipes for running Lobster without CMSSW.  I think at some point, some future generation is going to want to try this wouldn't CMSSW.  I understand that we might not easily be able to automate such an install, but it might be helpful at least to make a list of dependencies.  To this document, I'd be willing to contribute my recipe for running Lobster on earth sans CMSSW.

By the way, just to keep it in the record, I had a really weird issue with `virtualenv` and `pycurl` doing my CMSSW-less installation.  I'm not sure if it would happen for a CMSSW-ful installation.  Here it is for posterity:

Error: `ImportError: pycurl: libcurl link-time ssl backend (nss) is different from compile-time ssl backend (none/other)`

Solution:
```
pip uninstall pycurl
pip install pycurl --global-option="--with-nss"
```
This of course depends on the "ssl backend" in use so a different site might require "--with-openssl," etc.

**Comment by klannon** [comment]
OK, here is a tale of several wasted days and utter failure...

The setup I described above where I could install and run Lobster without CMSSW broke right before I could try my next big scale test.  This was basically on Christmas eve, taking what I thought would be a moderate to short amount of work to get a run going while I celebrated Christmas into an all consuming, unbounded attempt to debug why something that was working stopped working.  The error I had suddenly encountered was this:

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/afs/crc.nd.edu/x86_64_linux/python/2.7.8/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/afs/crc.nd.edu/x86_64_linux/python/2.7.8/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/afs/crc.nd.edu/user/k/klannon/.lobster/lib/python2.7/site-packages/lobster/commands/process.py", line 98, in sprint
    task_src = TaskProvider(config)
  File "/afs/crc.nd.edu/user/k/klannon/.lobster/lib/python2.7/site-packages/lobster/core/source.py", line 207, in __init__
    self.__dash = monitor(self.workdir)
  File "/afs/crc.nd.edu/user/k/klannon/.lobster/lib/python2.7/site-packages/lobster/cmssw/dash.py", line 77, in __init__
    self.__username = db.dnUserName(dn=id)
  File "/afs/crc.nd.edu/user/k/klannon/.lobster/lib/python2.7/site-packages/WMCore/Services/SiteDB/SiteDB.py", line 113, in dnUserName
    userinfo = filter(lambda x: x['dn']==dn, self._people())[0]
  File "/afs/crc.nd.edu/user/k/klannon/.lobster/lib/python2.7/site-packages/WMCore/Services/SiteDB/SiteDB.py", line 86, in _people
    people = self.getJSON("people", file=file, clearCache=clearCache)
  File "/afs/crc.nd.edu/user/k/klannon/.lobster/lib/python2.7/site-packages/WMCore/Services/SiteDB/SiteDB.py", line 71, in getJSON
    raise RuntimeError("URL not available: %s" % callname )
RuntimeError: URL not available: people
```

I spent a few hours today fully debugging it and all I can say is that it's something mysterious.  Hacking into the WMCore code with extra printout statements, I was able to determine that the real error is the following:`_ssl.c:320: Invalid SSL protocol variant specified.`

In trying to understand where this error is coming from, I reproduced the sequence of imports and calls in an interactive python session (using the same config, including virtualenv, etc. as lobster), and I didn't get the error.  That just works.  For posterity, here is the three lines of interactive python that should have triggered the error in a sane world:

```
from WMCore.Services.SiteDB.SiteDB import SiteDBJSON
db = SiteDBJSON({'cacheduration':24})
username = db.dnUserName(dn='/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=lannon/CN=490792/CN=Kevin Patrick Lannon')
```

Finally, in desperation, I nuked my Lobster installation, did cmsenv in a random 7x CMSSW release, and reinstalled lobster.  Now it works.

I don't understand this, and it makes me a little bit nervous.  I would argue that we currently don't really know what it would take to disentangle Lobster from CMSSW (i.e. if we wanted to hand it to ATLAS).  In other words, there are potentially some fairly fundamental pieces of lobster that only work properly when it's built on top of CMSSW.  Does everyone agree with that?

If I'm right about the above, then I think the main immediate action is that we just recognize that it will take some work to extract Lobster from within CMSSW.  We can make a fresh issue to note exactly that, and then return to using Lobster productively.  I think factorizing Lobster and CMSSW is not a fire I want to fight today (or even this week, month, etc.)

Thoughts?

**Comment by matz-e** [comment]
Yes, there are some fundamental pieces that currently only work with CMSSW. And I'd agree that it is too much of a pain to disentangle everything.

I think we have some separation already, and your issues seem to stem from the monitoring, which can already be disabled. But for fully supporting non-CMSSW operation, there would have to be quite the incentive…

**Comment by klannon** [comment]
I think we've gotten as far as we're likely too with this issue in the immediate future.  Generic Lobster is a project for another generation of students.  CMS Lobster is awesome, so lets continue to focus on that.
