### ISSUE TITLE
Problem Running Lobster without CMSSW: LOCALRT

### ISSUE THREAD

**Issue by klannon** [matz-e/lobster#257]
I was trying to run Lobster without doing `cmsenv` because I was running an MC production run where multiple releases were in use and it didn't seem sensible that I would set up some random CMSSW release to run this set of projects.  I had already done the `virtualenv` installation described in #256.  However, the code was crashing in `workflow.py` because, even though `sandbox release` was defined, it wanted to find `LOCALRT` in the environment when it read `sandbox release` from the config in case that value wasn't set.  I have a locally modified version where I have it check `sandbox release` and `LOCALRT,` and it only raises an exception if it can't find either.  Should I push that to the master branch or start a new branch with this change?  After making this change (and following the steps in #256) I was successfully able to run Lobster without setting up CMSSW first.

**Comment by matz-e** [comment]
Push it and close this issue, please!
