### ISSUE TITLE
Plotting Broken in VirtualEnv Installation

### ISSUE THREAD

**Issue by klannon** [matz-e/lobster#258]
I did the installation as described in #256 and although Lobster runs, the plotting is broken.  It seems like the installation scripts don't move the `data` directory from `commands` to the installation location, at least when working with `virtualenv` and `pip install .`  Manually copying the `data` directory to `.lobster/lib/python2.7/site-packages/lobster/commands` fixed the problem.  I don't know enough about Python setup wizardry to figure out (quickly) how to patch this.  Could someone help?

**Comment by khurtado** [comment]
There was a small typo in the setup.py script. This should be fixed now.

**Comment by annawoodard** [comment]
Good catch, Kenyi! It looks like magic words only work in commit messages. I'm closing the issue, it was fixed via c8711c9.
