### ISSUE TITLE
Event Generation Accounted as Overhead in LHE via cmsRun

### ISSUE THREAD

**Issue by klannon** [matz-e/lobster#266]
It looks to me like because of the strange way that at least some LHE events (run from gridpacks via cmsRun) are implemented, we erroneously call processing time "overhead".  Very detailed explanation below...  Mostly, I want to note this before the big scale test so that we don't panic and think the overhead is really high at the start.

I have observed that when making LHE events via cmsRun, at least for Madgraph/aMC@NLO that the process appears to proceed as follows:
   1. cmsRun starts up and prints some basic stuff to the log file.
   2. cmsRun forks (spawns?  I don't know if I have the right terminology here) a separate MadEvent process that actually generates the events and (I think) writes them to a temporary file.
   3. When the MadEvent process finishes, cmsRun picks up again and (again I think) reads in the temporary file produced by MadEvent and writes it out in EDM format.

In terms of the log file output, this looks something like this:
```
%MSG-i ThreadSetup:  (NoModuleName) 27-Dec-2015 16:16:26 EST pre-events
setting # threads 2
%MSG
==> using COND/Services/RelationalAuthenticationService for auth, sys 1
==> using COND/Services/RelationalAuthenticationService for auth, sys 1
   ______________________________________     
         Running Generic Tarball/Gridpack     
   ______________________________________     
gridpack tarball path = /cvmfs/cms.cern.ch/phys_generator/gridpacks/slc6_amd64_gcc481/13TeV/madgraph/V5_2.3.2.2/ttW012j_5f_madgraph_mlmMerging/v1/ttW012j_5f_madgraph_mlmMerging_tarball.tar.xz
%MSG-MG5 number of events requested = 8000
%MSG-MG5 random seed used for the run = 835633714
%MSG-MG5 number of events requested = 8000
%MSG-MG5 random seed used for the run = 835633714
%MSG-MG5 number of cpus = 1
Updating grid_card.dat...
Now generating 8000 events with random seed 835633714 and granularity -1
P2_gg_ttxwpqq_wp_qq
.
.
.
[a bunch of MG output omitted]
.
.
.
pdf reweighted cross-section  :99 5.68141
pdf reweighted cross-section  :100 5.82262
min/max:5.44399 23.0811
total 146952
-rw-r--r--  1 klannon campus 135229355 Dec 27 17:10 cmsgrid_final.lhe
-rw-r--r--  1 klannon campus  15044245 Dec 27 17:09 events_presys.lhe
-rw-r--r--  1 klannon campus    185811 Nov 23 22:26 gridpack_generation.log
drwxr-xr-x 15 klannon campus      4096 Nov 23 19:02 mgbasedir
drwxr-xr-x  3 klannon campus      4096 Dec 27 17:09 process
-rwxr-xr-x  1 klannon campus      2325 Nov 23 22:19 runcmsgrid.sh
-rw-r--r--  1 klannon campus       574 Dec 27 17:09 syscalc_card.dat

27-Dec-2015 17:13:22 EST  Initiating request to open LHE file cmsgrid_final.lhe
27-Dec-2015 17:13:22 EST  Successfully opened LHE file cmsgrid_final.lhe
Begin processing the 1st record. Run 1, Event 1, LumiSection 1 at 27-Dec-2015 17:13:22.886 EST
Begin processing the 2nd record. Run 1, Event 2, LumiSection 1 at 27-Dec-2015 17:13:22.889 EST
Begin processing the 3rd record. Run 1, Event 3, LumiSection 1 at 27-Dec-2015 17:13:22.894 EST
Begin processing the 4th record. Run 1, Event 4, LumiSection 1 at 27-Dec-2015 17:13:22.898 EST
```
The thing to notice here is that the job starts at 16:16, but doesn't print out that ti's opening files or processing anything until 17:13.  After that, the events are "processed" at a very high rate (many per second).  Looking at the `report.json` file, it looks like the "Processing" part is just the part that comes after the log file says the file was opened:
```
    wrapper start: Sun Dec 27 16:16:04 EST 2015
    wrapper ready: Sun Dec 27 16:16:14 EST 2015
    prologue end: Sun Dec 27 16:16:20 EST 2015
    stage in end: Sun Dec 27 16:16:20 EST 2015
    file opened: Sun Dec 27 17:13:22 EST 2015
    file processing: Sun Dec 27 17:13:22 EST 2015
    file requested: Sun Dec 27 17:13:22 EST 2015
    processing end: Sun Dec 27 17:13:56 EST 2015
    epilogue end: Sun Dec 27 17:13:56 EST 2015
    stage out end: Sun Dec 27 17:14:04 EST 2015
```
I also noticed during this processing that some of the steps in the timing breakdown come out negative.  Could this be because the time difference between "file processing" and "processing end" is only 34 seconds, but the log file output and report.json say the CPU time is 165.553 seconds?

**Comment by matz-e** [comment]
Yes, with our setup, this is currently accounted for as overhead. I've noticed it too, but forgot to mention that. I don't think we can do much about it without some work to introduce a corner-case…

In the `ExternalLHEProducer` used, [the LHE file is produced at the start of the run](https://github.com/cms-sw/cmssw/blob/6b16de370881dd8ef339d34811b3d1e176c02b80/GeneratorInterface/LHEInterface/plugins/ExternalLHEProducer.cc#L238), and the produced LHE file then [read in and converted](https://github.com/cms-sw/cmssw/blob/6b16de370881dd8ef339d34811b3d1e176c02b80/GeneratorInterface/LHEInterface/plugins/ExternalLHEProducer.cc#L155). Producing the LHE file is thus overhead, and turning the LHE xml file into an EDM file the real processing.

As for the negative times, we should look into that!

**Comment by matz-e** [comment]
Looking at the log again (we grab the time stamps out of the CMSSW log), I don't see a simple way we could account for this? Maybe we will just have to live with it. After the GS tasks are done, the overhead will only be a small fraction of the total processing time, too…

**Comment by matz-e** [comment]
I've taken out the CMSSW overhead in 64ce0a9af74aaa6d75f919aba72e416ad798c068, and this should now be captured by processing.
