### ISSUE TITLE
Bug in accounting for removed workers

### ISSUE THREAD

**Issue by klannon** [matz-e/lobster#269]
It looks like there is a bug in the plot that accounts for the reason workers are removed.  I think every removed worker is counted both as evicted and idled out.  See plots below:
![turnover-hist](https://cloud.githubusercontent.com/assets/5149849/12216756/8c1a3580-b6ba-11e5-9a95-e78000d65db3.png)
![worker-deaths-hist](https://cloud.githubusercontent.com/assets/5149849/12216758/91da9334-b6ba-11e5-8a52-f7a1b660ea6f.png)

It's easiest to see by looking at the first chunk of removed workers happening after 8:52 on the plot.  The upper plot shows 80 workers removed.  The lower plot shows 80 evicted and 80 idled out for a total of 160.  It looks like the evicted and idled out bars everywhere in the lower plot are identical in size.

**Comment by annawoodard** [comment]
It looks like we're plotting removed workers in the upper plot from `stats.total_workers_removed` in the WQ API, evicted workers in the bottom plot from `stats.total_workers_lost`, and idled out workers in the bottom plot from `stats.total_workers_idled_out`. [Here](http://ccl.cse.nd.edu/software/manuals/api/html/structwork__queue__stats.html) it looks like:
```
int 	total_workers_removed
 	Total number of worker connections that were lost or terminated by the master. 
int 	total_workers_lost
 	Total number of worker connections that were unexpectedly lost. 
```

@btovar will have to comment on the distinction here. It might be possible that there isn't currently a way to get at the number of workers evicted through the stats API.

**Comment by annawoodard** [comment]
My guess would be that `total_workers_lost` is eviction + idling out?

**Comment by matz-e** [comment]
Looking at recent plots, this seems to be solved, thus closing this issue.
