### ISSUE TITLE
Add committed cores to the plotting.

### ISSUE THREAD

**Issue by annawoodard** [matz-e/lobster#270]
We should add the number of committed cores to the plotting. It is available through the WQ stats API from `stats.committed_cores`. Maybe also add committed memory?

**Comment by matz-e** [comment]
Maybe it would be useful to have tasks running and committed cores on the same plot? With different scales?

**Comment by annawoodard** [comment]
I'm sometimes suspicious of whether the additional cognitive burden to the viewer of understanding a plot with double scales is worth the convenience of having it all together. But I think either way would be fine!
