### ISSUE TITLE
We should prepare a workflow summary table per-workflow

### ISSUE THREAD

**Issue by annawoodard** [matz-e/lobster#272]
![screen shot 2016-01-09 at 2 05 44 pm](https://cloud.githubusercontent.com/assets/5114833/12217820/4a87317a-b6da-11e5-8dda-2d91a3a65465.png)

Now that we have the nice per-workflow plotting pages, we should reflect it in the workflow summary table with the number of events written, etc separated per-workflow. This would let users see the effect more obviously of filters between workflows (i.e. losing events due to parton matching, etc).

**Comment by matz-e** [comment]
Good point. I'm thinking that will end up in a lot of JS (just swapping the images around already is a lot more than needed) - maybe we should generate a few different html pages - a Lobster overview, a task overview, task overview split by workflow. That'll be a separate issue though, I guess.
