### ISSUE TITLE
Add Disk Usage Plot to Merging Monitoring Plots

### ISSUE THREAD

**Issue by klannon** [matz-e/lobster#277]
This is present for processing jobs but not merging.  Disk usage plots are probably the most useful resource plot for merging jobs.  Is there a knob for controlling WQ disk resources for merging tasks?  Otherwise, we should probably make an issue for that too.

**Comment by matz-e** [comment]
There isn't a knob for that so far. We use the same sandbox as for regular tasks, and could estimate disk usage for merge jobs by `n * size(sandbox) + 2 * merge_size`, where the latter 2 could be exchanged for a 1 in case we stream the input files.

**Comment by klannon** [comment]
OK, I put this in its own issue (#278) since it's really an independent topic.
