### ISSUE TITLE
Negative Non-Processing CPU Times

### ISSUE THREAD

**Issue by klannon** [matz-e/lobster#280]
Sometimes we get negative "non-CPU processing" times (see below).  I don't know why for sure.  This is most obvious for LHE jobs where almost no time is spent in "processing" because of the screwy way those jobs run (i.e. MadEvent takes all the time before processing begins--counted as overhead).  The plot below is just for the LHE step.  I'm not sure if having multicore CMSSW makes this worse too (does our code no what to do with that?)

Is there a quick fix?  Longer term, this might point at the fact that we need to adjust the way we monitor CPU vs Wall times...How exactly is "non-CPU Processing" defined?

<img width="758" alt="processing" src="https://cloud.githubusercontent.com/assets/5149849/12487987/7822d02e-c037-11e5-831b-5c775be83489.png">

**Comment by matz-e** [comment]
Yeah, we have a problem there…

* As you can see [here](https://github.com/matz-e/lobster/blob/master/lobster/commands/plot.py#L861), we define the Non-CPU processing as:

        x['t_processing_end'] - x['t_first_ev'] - x['t_cpu']
* `t_first_ev` is extracted from the CMSSW log
* `t_processing_end` is set by the wrapper after running the executable
* `t_cpu` is from the [framework job report](https://github.com/matz-e/lobster/blob/master/lobster/core/data/task.py#L557). I think this is actually the overall CPU time, including what we'd call overhead.

How do make this smarter?

1. Without changing anything, we could multiply `t_cpu` by

        (t_processing_end - t_first_ev) / (t_processing_end - t_prologue)

   To get the fraction of CPU time corresponding to the processing interval
2. We could just use `TotalEventCPU` (which, of course, [has been renamed `TotalLoopCPU`](https://github.com/cms-sw/cmssw/commit/7929774b574320b93065dbe1ecc74d240057768b#diff-9cf8c18b93b97f0203ec77f48d4cfb3eL186)) (actually, no, maybe better don't use that) and `TotalJobCPU`, `TotalJobTime`. Then:

        t_overhead_cmssw = (t_processing_end - t_prologue_end) - TotalJobTime
        t_processing = TotalJobTime
        t_processing_cpu = TotalJobCPU

I've poked around your production run, and as an example for the `gs_step`, I'd get for (2):

    t_overhead_cmssw = 6106 - 6078.04 = 27.96
    t_processing = 6078.04
    t_processing_cpu = 5936.02

Where with our current method, I have:

    t_overhead_cmssw = 114
    t_processing = 5992
    t_processing_cpu = 5936.02

For LHE (new way):

    t_overhead_cmssw = 1150 - 1138.43 = 11.6
    t_processing = 1138.43
    t_processing_cpu = 136.955

LHE (old way):

    t_overhead_cmssw = 1127
    t_processing = 23
    t_processing_cpu = 23 - 136.955 = -113.955

I guess it boils down to how do we define things? If we do (2), we can also skip parsing a text file, and simplify our code…

For better arguments: we currently rely on counting the processing as the time from opening the first input file to the end of the executable running. Then we take another metric, measured differently, and subtract it from that. We should really stick to one way of measuring things, and I would say that CMSSW should be our preference.

**Comment by klannon** [comment]
:+1: 
I completely agree with the basic overall approach.  One minor question: how does multithreaded CMSSW impact this?  For example, if you run 4 cores for 2 minutes is TotalJobCPU = 2 min or 8 min?

**Comment by matz-e** [comment]
I think that CMSSW takes this already into account - as in, the comparisons I made above were a mix of taking the CMSSW measurements and comparing them to timestamps in the log. I think your GS tasks use 4 cores, so in my opinion, the numbers match up (for efficiency measurements).

**Comment by matz-e** [comment]
And to answer your questions, how I read the output it would be 4 cores for 2 min: `TotalJobCPU` of 2 min.

**Comment by khurtado** [comment]
@matz-e: Are you sure?  Here is some hypernews thread [1] from a year ago where they show 4 core jobs with `TotalJobCPU` values greater than `TotalJobTime` by a factor of ~Ncores:

```
<Metric Name="TotalJobCPU" Value="22713.6"/>
 <Metric Name="TotalJobTime" Value="6344.54"/>
```
So, a year ago at least, I think the answer to Kevin's question would have been 8 min.

I think dashboard still uses: `TotalJobCPU` / (Ncores * `TotalJobTime`) for the efficiency calculation nowadays (which can sort of be verified by the very low dashboard efficiency calculations for the recent ND 4 core jobs [2] compared to what would be expected if the CMSSW report were averaging CPU time from all cores rather than adding them up). Which makes me think maybe those GS tasks didn't really use 4 cores.

[1] https://hypernews.cern.ch/HyperNews/CMS/get/wmDevelopment/672/2/1/1.html
[2] http://dashb-cms-jobsmry.cern.ch/dashboard/request.py/dailysummary#button=cpuefficiency&sites%5B%5D=T3_US_NotreDame&cores%5B%5D=4&sitesSort=3&start=2016-01-16&end=2016-01-31&timerange=daily&granularity=Daily&generic=0&sortby=0&series=All

**Comment by khurtado** [comment]
So, FWCore uses RUSAGE_SELF for calculating the CPUtime [1]:

````
RUSAGE_SELF
Return resource usage statistics for the calling process, which is the sum of resources used by all threads in the process.
```
[1] https://github.com/cms-sw/cmssw/blob/b737576f0733ceeff0a9ceea44c54f4d35459ef2/FWCore/Services/plugins/Timing.cc#L92-L101

**Comment by matz-e** [comment]
@khurtado, I think you're on to something there. I've just consulted a few man pages and poked around in more of the reports, and I don't see anything where the CPU time exceeds the real time. The executable log says though that the # of threads is set to 4… I'll try to do some more manual running/investigation.

**Comment by matz-e** [comment]
OK, so far, passing `cmsRun` arguments do use more than one core do not change anything for me running a GS job, which is different from what I recall.

**Comment by matz-e** [comment]
Grr… I found that `numberOfStreams = cms.untracked.uint32(0)` is needed in the `pset` to give me CPU time > job time. Now with GS jobs, the speedup does not seem to be significant.

**Comment by khurtado** [comment]
@matz-e  So, I assume `numberOfStreams` is "1" by default. Shouldn't `numberOfStreams` be equal to the number of cores? Does "0" do that? Or how does that work? Just trying to understand...

**Comment by matz-e** [comment]
It is not set at all by default, I think. [If it is present in the parameter set, and equal to 0, it'll get set to the number of threads.](https://github.com/cms-sw/cmssw/blob/c3755875539396947029724dda804e6a388dfdf0/FWCore/Framework/src/EventProcessor.cc#L430)

**Comment by khurtado** [comment]
@matz-e Thanks! I see a `nStreams =1` before the line you pointed out though. In any case.. "0" indeed seems to do what we need.

**Comment by matz-e** [comment]
Ah, you're right. My mind translated that into -1, somehow, and reading the rest of the code seemed make sense, still.

**Comment by matz-e** [comment]
@klannon Just now looking at the RECO with 76, which works multi-threaded. In the plots, should CPU time be divided by the number of cores, or should the walltime be multiplied by the number of cores? I would lean to do the latter – total use of time on the worker seems more appropriate.

All other times I would leave how they are currently – using one core. That gives a better breakdown of the timeline without having to do some math trying to figure out how long a task actually runs. Thoughts?

**Comment by khurtado** [comment]
@matz-e JFYI, dashboard does the latter.

**Comment by matz-e** [comment]
Thanks, @khurtado, I'll keep in line with that. Plotting will then show, in the case of a 4-core task (made up):

* runtime: 9 min
* overhead: 2 min
* CPU processing 20 min
* Non-CPU processing 8 min

**Comment by klannon** [comment]
I'm trying to decide what makes the most sense in the context of the actual monitoring plots we've been making for Lobster.  I just went to look at plots from one of your recent runs.  I think the problem is that we're trying to mix two different types of quantities: times that tell you how long different phases of the task too (i.e. wall-time based) and times that tell you whether you were mostly computing vs doing other stuff (CPU vs Wall time).  I think maybe it would be better to try to keep these distinct.  Therefore, I suggest that for the task timing we only report wall time values.  I would not even try to break processing up into CPU vs non-CPU times.  I'd just try to detect when processing starts and when it finishes.  I think this ensure that no matter what happens, we get all positive entries (assuming there are no issues with time-stamp mistakes, etc.).

Then, I would make a distinct plot that I would call something like CPU efficiency where I'd take the ratio of CPU/(nCores*wall time).  Probably it makes sense to do this just for the processing part based on CMSSW timing information, but it might be worth considering whether we also want to report the overall job number from the resource monitor as well.  I go back and forth on this because the difference between the processing CPU efficiency and the overall one would just be any extra components (like output transfer wait which are recorded elsewhere anyway).  In any case, I'm certainly open to suggestions.

Let me know what you think.

**Comment by matz-e** [comment]
Sounds good! So in the timeline, I will take out CPU/Non-CPU processing. That'll leave total processing time as a plot there. Then I can add a (executable/CMSSW) processing efficiency just like you describe and add it to the task resources part. This is the part where the user has input, like adjusting number of cores…
