### ISSUE TITLE
Plotting Code Performance Improvements?

### ISSUE THREAD

**Issue by klannon** [matz-e/lobster#281]
So, for long-duration runs, the plotting can get really slow.  How slow?
```
2016-01-22 14:56:40 [DEBUG] lobster.plotting: reading database
2016-01-22 14:57:00 [DEBUG] lobster.plotting: finished reading database
2016-01-22 14:57:13 [INFO] lobster.plotting: reusing previously calculated cpu time stats.
2016-01-22 15:28:03 [INFO] lobster.plotting: Copying sample logs for exit code -11
```
So, the DB access takes ~20 sec and the CPU stats calculation takes ~30 min.  (Bear in mind that it had been ~8 hours since I'd last run a plot, which may have some impact.)

We should think about whether there are any performance gains that we could make that would be easy to implement and would dramatically speed things up.  For the plotting of CPU, I wonder if we couldn't make a big difference by being more intelligent with finding the first job edge.  Rather than starting at the left of the plot and searching each bin to the right, we could do a binary search for the first edge.  Or, since we tend to plot predominantly new jobs, we could search for the first bin right to left instead of left of right.

**Comment by matz-e** [comment]
Yes, we could do such improvements. Note that the plot is already incremental, as in only the tasks that finished since the last time are processed (need to double-check). Instead of a binary search, finding the bin should in fact be O(1) for start and end bin, since the histogram is in 1-minute bins since the start of the run and will get re-binned to be displayed on the plot page.

**Comment by matz-e** [comment]
I just copied your database… this is totally not OK in terms of performance! (4 minutes for 1000 tasks…)

**Comment by matz-e** [comment]
Ouch. I just switched it to a few numpy methods… and filling the histo with 455k tasks takes 8 seconds now (there are a couple seconds more lead time to do the vector division to get the CPU/Wall ratio for all .5G tasks)
