### ISSUE TITLE
Lobster website is down.

### ISSUE THREAD

**Issue by annawoodard** [matz-e/lobster#285]
See [https://lobster.crc.nd.edu/](https://lobster.crc.nd.edu/).

**Comment by matz-e** [comment]
Now that we've moved the docs, maybe we should add the content of the site to `README.md`? We could make it fairly compact, and then would not rely on the CRC.

**Comment by annawoodard** [comment]
Agreed!

**Comment by matz-e** [comment]
Not any more?
