### ISSUE TITLE
Standardize wrapper script

### ISSUE THREAD

**Issue by annawoodard** [matz-e/lobster#291]
@khurtado has encountered errors due to inconsistencies between bash and sh on some remote sites. @btovar pointed out they are probably from our use of line continuations and double brackets. We need to standardize our wrapper script. @dthain suggested sending our own shell.

**Comment by matz-e** [comment]
I think that @btovar may be right that the `[[` may be the culprit.  [What I found](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html) says the **may** be supported, but don't have to.

**Comment by matz-e** [comment]
@khurtado can you point me as to which shell you found that to be the case? Even busybox has a `[[` command…

**Comment by matz-e** [comment]
Nevermind… apparently, dash is present on RH systems, too, and more barebones than busybox? WTH?
