### ISSUE TITLE
Add cleanup for intermediate files

### ISSUE THREAD

**Issue by annawoodard** [matz-e/lobster#313]
In some projects with dependent workflows, the user may have intermediate outputs that he or she doesn't care about. These are impossible to cleanup by hand until the project is finished, as the user can't know which files are still needed for subsequent tasks. We should add a knob in the configuration which notifies the master these should be cleaned up as dependent tasks finish. This will be important for large projects in order to conserve space on the storage element.

**Comment by klannon** [comment]
+1 +1 +1 +1 +1 +1 +1 +1 +1

**Comment by klannon** [comment]
OK, just noticed that I could add reactions directly to issues, but it only let's me add +1 and I wanted more weight.  :)

**Comment by matz-e** [comment]
How about `+inf`?

**Comment by annawoodard** [comment]
I started implementing this. In doing so, I am reminded that we already have a knob `merge_cleanup` which allows the user to specify whether or not to delete the original files after merging. I cannot imagine a scenario where you'd want to keep the original files after merging, and I think it makes the documentation more confusing (intermediate cleanup vs merging cleanup). My preference would be to remove this option and always delete merged files and only have one cleanup option which refers to cleaning up intermediate processing/production files. Does anyone have any objections?

**Comment by klannon** [comment]
Will it be possible to independently specify the following behaviors?
 1.  Don't merge intermediate files, but clean them up when you're done.
 2.  Merge intermediate files and don't clean up (i.e. you want to save them long term)
 3.  Merge intermediate files, but then clean up the merged files.

I think (1) and (2) would be the regular cases.  (3) would only come up if we had files that we wanted to merge before feeding to the next processing step, but didn't want to save afterwards.  I guess I don't know whether (1) or (3) would be the better approach for throwaway files.  If you have some intermediate stage (say the output from DIGI) is there any advantage to merging the output before feeding it to RECO?  Or would you generally only merge things you might want to keep (LHE, RECO, miniAOD, etc.)?

**Comment by klannon** [comment]
For clarification,  everything above assumes you clean up unmerged files after making the merged versions...

**Comment by annawoodard** [comment]
> 1. Don't merge intermediate files, but clean them up when you're done.
> 2. Merge intermediate files and don't clean up (i.e. you want to save them long term)
> 3. Merge intermediate files, but then clean up the merged files.

I think these three cases are covered by my proposed single cleanup knob (along with the existing merge knob):

1. `cleanup=True` (do not specify a merge size)
2. `cleanup=False`, `merge_size=XXX`
3. `cleanup=True`, `merge_size=XXX`
