### ISSUE TITLE
Add new `work_queue_stats` times to task summary pie chart

### ISSUE THREAD

**Issue by annawoodard** [matz-e/lobster#323]
@btovar has added `total_exhausted_execute_time` to the `work_queue_stats` struct in cooperative-computing-lab/cctools#1273, we should put this into the task summary pie chart.

**Comment by matz-e** [comment]
I'm wondering how this would properly get accounted for? Do we need to subtract that from the current "eviction time"?

**Comment by matz-e** [comment]
Sorry, should have read the other channels. I see now that we have all the right stats in place :)

**Comment by annawoodard** [comment]
Let's switch to using `total_time_until_worker_failure = task.total_cmd_execution_time - task.cmd_execution_time - task.exhausted_execute_time` for eviction which @btovar has added in the above mentioned PR. Since these are minor changes, let's include that to be updated in order to fix this issue. Here's what @btovar said on Slack regarding this quantity.

> > How close do you think that is to the actual eviction time? Are there other things grouped in there? Is there a way we could get at the actual eviction time?

> It should be pretty close.  Counted there are disconnections because worker errors, network errors, or eviction. The master can't really tell from those, though. However, the worker Should Not Have Any Errors (TM), and network errors are uncommon. That said, if you have the condor log, probably you could get a better estimate.

**Comment by annawoodard** [comment]
From @btovar on Slack, here are the new quantities:
```
t.total_time_until_worker_failure            Accumulated time for runs that terminated in worker failure/disconnection.
t.exhausted_attempts              Number of times the task failed given exhausted resources. (edited)
t.total_cmd_exhausted_execute_time      Accumulated time spent in microseconds spent in attempts that executed resources. (edited)
stats.total_exhausted_attempts
stats.total_exhausted_execute_time           Total time in microseconds workers spent on tasks that exhausted resources.
```
