### ISSUE TITLE
Optional chirp stage-in server for file-based jobs.

### ISSUE THREAD

**Issue by annawoodard** [matz-e/lobster#33]
We could add an optional stage-in chirp server for file-based jobs.  It could be dealt with in cmssw/data/job.py in the same way for processing and merge jobs, instead of being done in cmssw/data/merge_cfg.py for merge jobs only.  What do you think, @matz-e ?  Would we be overcomplicating things, or is the speedup worth it?

**Comment by matz-e** [comment]
I think we can close this now?  This should work!
