### ISSUE TITLE
Do not try to run on files that don't exist

### ISSUE THREAD

**Issue by annawoodard** [matz-e/lobster#330]
I haven't done any sleuthing yet, so I'm not sure where this is coming from, but I have quite a few [jobs](http://www.crc.nd.edu/~awoodard/lobster/ttZ/v2/a/logs/9539.log) that are failing because they are trying to run over files that don't exist, so it seems like something isn't getting updated correctly somewhere.

**Comment by annawoodard** [comment]
This problem was introduced by me in #322. We have a many to one mapping of jobs to input files, and we're deleting the input files after the first job that reads it uses it. 😩

**Comment by matz-e** [comment]
Ouch :( sorry, I didn't see that when looking at the PR.

**Comment by annawoodard** [comment]
Sorry for breaking Lobster! I'll look at this now.
