### ISSUE TITLE
Clarify `configure` logging messages.

### ISSUE THREAD

**Issue by annawoodard** [matz-e/lobster#364]
We currently have:
```2016-05-16 10:12:46 [INFO] lobster.configure: check the log of the main process for success```

It would be more helpful to have something like:
```2016-05-16 10:12:46 [INFO] lobster.configure: check the log of the main process for "configure success" or "configure failure"```

So that the user would know what to search for in the log.

**Comment by matz-e** [comment]
How about adding a output handler to produce a separate log, just for this?
