### ISSUE TITLE
Improve monitoring of what the master is spending its time on

### ISSUE THREAD

**Issue by annawoodard** [matz-e/lobster#365]
The current fraction hist is not very illuminating when the master is under heavy load, because it is mostly 'other' (which is exactly when it would be helpful):
![fraction-hist](https://cloud.githubusercontent.com/assets/5114833/15292983/cbb4b1e0-1b53-11e6-9a88-631e6bbf5dea.png)

We should add the time it spends in `obtain` and `release`, etc.

**Comment by annawoodard** [comment]
We should also clarify that 'creating', etc, is time spent by WQ on creating, while the time we spend assembling the tasks to pass to WQ might be higher.

**Comment by matz-e** [comment]
Um… [no](https://github.com/matz-e/lobster/blob/master/lobster/commands/process.py#L268-298). It's the time spent obtaining. Similarly for returning.

**Comment by annawoodard** [comment]
Ah, thanks for pointing that out. Well, then it's even more mysterious, and we should figure out where the time is going and plot it.

**Comment by klannon** [comment]
Indeed, we need to name 'other' because anecdotally, when the above graph is dominated by 'other' Lobster seems to be struggling to keep up.

Any ideas what else we could measure and break out in the plot?

**Comment by matz-e** [comment]
I think that we have most parts of the main loop in Lobster covered pretty well – but the WQ sending/receiving/idle is the only WQ part we cover. I think we also need to measure whatever else WQ does and then subtract `idle + sending + receiving`. Then we should include all other Lobster activities (getting remaining work, doing some side checks), too.
