### ISSUE TITLE
Truncate command output in memory

### ISSUE THREAD

**Issue by matz-e** [matz-e/lobster#368]
To keep excessive disk consumption down.

**Comment by annawoodard** [comment]
Before I forget the motivation for this next time we `condor_ssh_to_job` and can't see all the stdout, I'll remind my future angry self here that I almost brought `condorfe` down with 150+ GB stderr files courtesy of GEANT.

I think it would be preferable to continue writing a selection of the stderr as the truncating is happening. So I'd vote to write out the first X lines, then begin truncating and only append every 100 / 10000 lines or something like that. That would still give us an idea of what's going on.

**Comment by klannon** [comment]
So, as you noted on Slack, I'm against truncating the log output.  My preferred solution would be to talk to cmsRun and convince it not to write so much out.  There are many knobs in the logging to get a handle on this; see for example:
https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideMessageLogger#Features_List

I showed Mike your statement about "150+ GB stderr files courtesy of GEANT" and he said there's no way that should be happening.  I think we're just missing a switch in our config to suppress this.  Regardless of what we do with truncation, we should dig around to fix this.

What about this for a compromise?  If we implement truncation, make sure the implementation is such that the only files that get truncated are ones that would be large enough to start to cause problems.  In other words, don't truncate when you think that the size is so large keeping the whole file isn't helpful; instead only truncate when you know that keeping the whole file will be harmful.  (I recognize this isn't boundary between these two, but that's OK.  I'm just looking to steer the mindset.)

Does that make sense?

**Comment by matz-e** [comment]
How do you define being large enough to cause problems, though? IMO, anything above 10k lines contains output that is never going to be looked at really… and I don't really want to measure the string size in memory, either.

This output needs to be buffered too, somewhere. A few months ago, WQ would have refused to give us the output, giving an error saying that it's size was too large (4 GB unpacked). Also, as much as I'd like it, using the `MessageLogger` is not enforced (neither will all custom scripts use it), and I've seen various prints sprinkled throughout code.

I agree that truncating is ugly, but I think it's a sensitive default. If someone thinks they missed something in the 10-20k lines we can easily provide (this is more than CRAB does), then they should seriously re-think their logging strategy. But I'd rather have tasks not fail because of too much output than tell someone to remove more of their `std::cout` statements. I think that from a users perspective, truncated output will lead to a more "natural" learning curve/provide a better nudge than someone complaining about tasks failing from a mysterious reason. If I were to encounter the latter, I'd be unhappy and complain loudly to devs, with the former, I'd be more inclined to keep my mouth shut and grudgingly take some output out (or have smaller tasks).

**Comment by klannon** [comment]
Well, I think that we're not saying inconsistent things here, but keep in mind that I'm coming at this very pragmatically.  I would be satisfied if we did two things:
 1. Set the number of lines to be kept threshold at something like 2-3 times the size of the "typical" output file from our successful jobs.  That way, most of the time you'll have everything.
 2. Don't treat truncation as the solution to this particular problem but also spend some time trying to understand what's going on in these jobs.  Your boss has some interest in this as I've been showing him some of the discussion and he thinks there is no way this should be happening.

Also, I think we need to consider whether making it easy for users to run code in Lobster that generate hundreds of GB of text output in logs is a good thing.  I would argue that jobs that produce that much output are bad and that truncating the logs is just masking a problem (that the user might be completely unaware of).  Logging at that level seems like it must slow the job down.  Maybe there are some circumstances (all of them) where a job should fail for trying to write a 100 GB log file.  (Although it would be good to make sure that it's clear to the user what went wrong...)

And to answer your question, I always read every line of every log file, even the 10k line ones.  Don't you?  But seriously, while I might not read all the lines, I often grep them when I'm trying to understand things.  The problem with truncation is that it's like a prescale in the trigger--you don't get to choose what information is dropped, so it might be the key thing you're looking for.

**Comment by matz-e** [comment]
Hm… I'm curious as to what the "typical" output is. To make the problem more obvious, I think we could set a flag in our task report that the master reads and prints a warning/error log? Although then it would be best to have an additional log file with just warnings/errors (I think this would be a good idea anyways and easy to do thanks to the logging interface).

We could also highlight this in the plotting if we save said flag to the database and monitor it?

**Comment by annawoodard** [comment]
I haven't had time to look into the cause yet in detail, but I'll just add that writing out the 150+ GB files only happened in some kind of error state, which was so bad that the logs never got back anyways. My entire working directory (with all returned successful and failed logs) is only ~13 GB.

**Comment by matz-e** [comment]
Revisiting some old issues while my code is "compiling"… for the sake of simplicity, it would be easiest to not do this (truncating in memory gets ugly, and there are some weird cases where this could happen already).

After the discussion of supporting another institute, I'm inclined to follow @klannon's path and take out any and all truncating. Making code simpler, with the following issues that may arise:

* I'm not sure how WQ handles too much stdout anymore (@btovar?), if it fails gracefully or not
* I would still keep writing the output to disk first to avoid any deadlocking issues with python's `subprocess` module; This could lead to tasks getting evicted due to excessive stdout, which will disguise what's really going on? Alas, that has been how Lobster behaves for quite a while.

**Comment by annawoodard** [comment]
:+1: for simplifying things
