### ISSUE TITLE
Rework the task wrapper script to quit when one step fails.

### ISSUE THREAD

**Issue by matz-e** [matz-e/lobster#373]
I'm currently looking into why my merge tasks fail (it's xrootd access to the storage element, I think).  Currently, out tasks script just proceeds through the steps as if nothing happened. I think we should rework this to stop at the first error. My suggested changes:

1. The main flow of the script should be a bunch of function calls, no real logic (maybe beyond the CMS code distinctions for now), like:

        config = json.load(…)
        data = {…}
        copy_inputs(config, data, …)
        execute_prologue(config, data, …)
        …

2. Instead of using the context to set the error state, wrap the above functions, and update mona-lisa accordingly, if needed:

        @quit_on_failure(exit_code=210)
        def copy_outputs(config, data, …):
           …

**Comment by annawoodard** [comment]
:+1: :+1: :+1: :+1:
