### ISSUE TITLE
Make sure all files we create end in newlines.

### ISSUE THREAD

**Issue by annawoodard** [matz-e/lobster#379]
See [here](http://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline). I think that `parameters.json` is not currently compliant. Is there anything else?

**Comment by matz-e** [comment]
Will we enforce emacs users to [fix their config](https://www.gnu.org/software/emacs/manual/html_node/emacs/Customize-Save.html) too? 😄

**Comment by klannon** [comment]
If we could enforce the behavior of users we wouldn't need most of Lobster.  :)
