### ISSUE TITLE
Notify user on errors

### ISSUE THREAD

**Issue by matz-e** [matz-e/lobster#38]
Often, the lobster master dies quietly without anyone noticing.  We already catch exceptions on a very high level, where we could also notify the user via email or other means.

This may be helpful: https://docs.python.org/2/library/smtplib.html#smtp-example

**Comment by matz-e** [comment]
Another suggestion: We could send an email when the proxy is about to expire in 12, 8, 4, 0 hours… I've had that happen to me a bunch of times.

**Comment by matz-e** [comment]
@klannon pointed [this](https://api.slack.com/community) out to access slack…

**Comment by annawoodard** [comment]
@WenzhaoLi: @matz-e pointed out this might be a fun one for you.

**Comment by WenzhaoLi** [comment]
@annawoodard @matz-e Could you point me to place in lobster where I should add the new code?

**Comment by matz-e** [comment]
@annawoodard Maybe this could end up in `monitor/email`? That's where I think it could fit best ATM… we could always re-factor it a little later…

**Comment by annawoodard** [comment]
Sounds good to me.
