### ISSUE TITLE
Allow file-based configuration updates (as opposed to command-line-based ones)

### ISSUE THREAD

**Issue by annawoodard** [matz-e/lobster#382]
I would find it easier to make changes to my configuration file and ask Lobster to reload it, rather than doing it at the command line. That has the added benefit that I can more easily see what the current settings are (I guess you can also see it in the configuration linked from plotting, but it would enforce that everything is consistent.)

**Comment by matz-e** [comment]
I may have some ideas… I think we can pull this off if everything is based off of the configurable class. We could actually remove the `configure` command, copy the configuration to the working directory again and then monitor it for changes, just like `work_queue_factory` does?

**Comment by annawoodard** [comment]
That would be my vote!

**Comment by annawoodard** [comment]
Another small issue with the configure command is that there's no way for new users to know the structure a priori from the configuration file. For example, I have:
```
workflows=[lhe, gs, digi, reco, maod],
```

in my configuration, but I need to use

```
lobster configure workflows.digi_step.category.tasks=1000 ttW.py
```

rather than
```
lobster configure workflows[2].category.tasks=1000 ttW.py
```

**Comment by matz-e** [comment]
Good points! It's pretty opaque! I've listed some examples in the docs, but I don't think they capture everything…
