### ISSUE TITLE
CMSSW 7_1_X does not provide XrdStatisticsService

### ISSUE THREAD

**Issue by matz-e** [matz-e/lobster#396]
Makes current pset modifications crash the tasks.

**Comment by matz-e** [comment]
I think we should be able to query the possible plugins in python and conditionally set this, somehow…

**Comment by klannon** [comment]
Would it be more expedient just to check against CMSSW version? This 
will break the MC production chain.

**Comment by matz-e** [comment]
Well, currently the version of the MC chain that is in git is broken due to this. I'll try to figure out how to get around it when my next slice of free time comes around. Possibly tonight, if the kid shuffle and catching up with the multi-leptons doesn't completely exhaust me.

**Comment by matz-e** [comment]
(I noticed this when I was trying to run the MC chain to test the factorized-out task creation algo)

**Comment by klannon** [comment]
Got it.  If it's just a matter of figuring out the CMSSW version and comparing against some threshold (74x?), I could probably implement a quick fix.

**Comment by klannon** [comment]
(But if you get the chance, don't wait for me to do it!)

**Comment by matz-e** [comment]
I had looked before in the office, but couldn't even see which branch that plugin file was already in…

**Comment by matz-e** [comment]
Meh. Seems like the best way to solve is to take the environment and look for the CMSSW version, manually splitting and comparing it to `7_4_X`, which seems to be the first release the stats service was in. I'll try to file a PR soon, as long as my tasks come back right.

**Comment by khurtado** [comment]
You could alternatively rely on `edmPluginHelp` to tell you whether the plugin exists in the environment or not. I imagine one could in principle build a newer version of `XrdAdaptor` (the package is there since `5_x_x`or so, but XrdStatisticsService was added by default on `7_4_x` as you pointed out, sorry I didn't notice that before committing) so version comparisons would not be the best option in the case a user provides a sandbox with it.
```
edmPluginHelp -q -p XrdAdaptor::XrdStatisticsService
```

**Comment by matz-e** [comment]
I considered that… but then we'd have to run another external program to conditionally modify the pset… I don't think that we're going to use anything < `7_4_X` for that much longer, so I think a short conditional is best. Users who build their own updated `XrdAdaptor` can also modify Lobster, /me thinks.

**Comment by khurtado** [comment]
Mmmhh... I was thinking on running it on the wrapper and set some environment variable that `task.py` can read so that you don't start another subprocess, but you are right this is too much trouble for something that might not be needed in short.

**Comment by matz-e** [comment]
It is a lot… especially since we need to keep track of things in two places then… I'm waiting for one of the `7_6_X` tasks to go through the system, then I'll commit a fix.
