### ISSUE TITLE
User Documentation Mentions Nothing About Terminate!

### ISSUE THREAD

**Issue by klannon** [matz-e/lobster#409]
Probably good to put a short note after telling people how to stop, how they can shut lobster down.  Possibly a good item for @WenzhaoLi?

**Comment by annawoodard** [comment]
We should also clarify that the point of using `lobster terminate` is to give your master a chance to clean up and exit gracefully-- but it may take a few minutes. This is useful if you need to stop your master but plan to restart the same project. If you know that you are going to throw the working directory away anyways, feel free to use `kill -9 <process id>`.
