### ISSUE TITLE
For non-DAS jobs, check if we can access the file via xrootd.

### ISSUE THREAD

**Issue by annawoodard** [matz-e/lobster#41]
Serguei has setup an xrootd server-- for non-DAS jobs, we should check if we can access input files via xrootd. If so, we should use that instead of copying them to the worker either via WQ or Chirp.

**Comment by matz-e** [comment]
Already partially addressed in 95cda8faf226a3d662de033ea10af0579fd35d24, using XrootD to allow to stream input files.  This should cover most of our use cases, so I'm closing this for now.
