### ISSUE TITLE
Correct documentation on running `work_queue_factory`.

### ISSUE THREAD

**Issue by annawoodard** [matz-e/lobster#411]
I use bash with:
```
nohup work_queue_factory -T condor -C factory.json >& factory.log &
```

@klannon uses tcsh with:
```
work_queue_factory -T condor -C factory.json >&! factory.log &
```

@matz-e uses bash with:
```
export what=prod; nohup work_queue_factory -T condor -o /tmp/matze_pool_$what.debug -C pool_$what.json > /tmp/matze_pool_$what.log &
```

None of these match the instructions in the documentation. We need to correct it, with caveats for various shells.

**Comment by matz-e** [comment]
I don't think we need caveats for different shells per se. Fix in the work with new `label` handling.

**Comment by klannon** [comment]
Well, in defense of shell confusion, many new users don't even appreciate the differences between bash and tcsh.  The CRC defaults you to tcsh.  So most new users try to follow the directions and fail.  This leads to frustration.  It would be nice to alleviate some of this frustration.  I know, you'll say everyone should just switch to bash, but by now, you should know that's not the way the world works...

**Comment by matz-e** [comment]
Doesn't `nohup` work for `tcsh`, too? The only really shell-specific thing in there is stderr re-direction.

**Comment by matz-e** [comment]
This is what I propose in the PR:
```
nohup work_queue_factory -T condor -M lobster_$USER.* -o /tmp/${USER}_factory.debug -C factory.json > /tmp/${USER}_factory.log &
```
And I don't see why that shouldn't work in `tcsh`.

**Comment by klannon** [comment]
So let me continue to expose my ignorance.  Why do you need nohup?  If you redirect stdout and stderr, logging out doesn't kill your process, right?

**Comment by matz-e** [comment]
It does in bash. Does it hurt to have it in there for tcsh? I'm sure that you can configure tcsh to kill background processes on logout, too.

**Comment by matz-e** [comment]
(you can configure bash to behave like tcsh, too)

**Comment by klannon** [comment]
OK, well, I have no objections to that approach then.
