### ISSUE TITLE
Lobster Wrapper Hard-Codes OSG 3.2 while T3 is at OSG 3.3

### ISSUE THREAD

**Issue by klannon** [matz-e/lobster#415]
At the minimum, we should update the hard-coding as OSG 3.2 is deprecated in Aug 2016.  It would be nice not to have the version hard-coded.  For example, Lobster could use the version that's used on the node where the master is run?  Thoughts?

**Comment by matz-e** [comment]
Can we find that out reliably? We could make that an option, and pass it along as an environment variable?

**Comment by matz-e** [comment]
I guess `OSG_LOCATION` could be a good indicator.

**Comment by klannon** [comment]
Right, I think both of those would be desirable.  By default, Lobster could use the value in `OSG_LOCATION` and if that isn't set, then Lobster could issue a message to the user requesting them to set a specific version via a configuration option.  The user could also use the config option if she or he wanted to override the default behavior.  I haven't had a chance to look, but do we already have a method for passing options into the wrapper script?

**Comment by matz-e** [comment]
Yes, we actually do. Should be a quick fix.

**Comment by klannon** [comment]
Well, I don't think it's an emergency so would this be another quick thing for @WenzhaoLi to try?

**Comment by matz-e** [comment]
Sure. We need an option defaulting to `None` [here](https://github.com/matz-e/lobster/blob/master/lobster/core/config.py#L215), some environment checking and member variable setting [here](https://github.com/matz-e/lobster/blob/master/lobster/core/source.py#L145) — throw an `AttributeError` if `OSG_LOCATION` is not in the environment and the configuration variable is not set. Then said member variable needs to be put in the task environment [here](https://github.com/matz-e/lobster/blob/master/lobster/core/source.py#L418) (like `LOBSTER_OSG_LOCATION`), and then, finally, used in the wrapper [here](https://github.com/matz-e/lobster/blob/master/lobster/core/data/wrapper.sh#L128).

Now do we want to be mindful of different RH versions being used? Then there has to be a little bit of shell magic to make everything match up.

**Comment by klannon** [comment]
I think we do want to be a little bit careful for two reasons:
 1.  We can't be sure we'll be running on exactly the same version of Linux as the submitting machine.
 2.  We don't know for sure that the submitting machine will be using OASIS and we don't want to accidentally point our worker job at some locally installed OSG version.

What if we parsed `OSG_LOCATION` to extract the version number (e.g. `3.3`) and passed that to the task wrapper to replace the hard-coded `3.2` [here](https://github.com/matz-e/lobster/blob/master/lobster/core/data/wrapper.sh#L130)?  We could also extract the specific version number (e.g. `3.3.13`) or we could just leave it at `current` as we have now.  Thoughts?

**Comment by matz-e** [comment]
That sounds good, too. Just an `LOBSTER_OSG_VERSION` would be pretty simple, and no cross-checks needed for the whole path to be in `/cvmfs`.

**Comment by klannon** [comment]
OK, well in the spirit of not fixing things that aren't broken, why don't we leave the minor version at `current` and just pull out the major version from either the `OSG_LOCATION` on the submitting machine or, if set, the config variable.  The rest is basically as @matz-e describes above.  @WenzhaoLi, can you add this to your list of things to try?  Don't hesitate to ask any questions.  Follow the usual procedures, making a branch, pushing your changes onto the branch, and making a pull request (PR) so @matz-e and @annawoodard can check your work before we merge it into the master.

**Comment by WenzhaoLi** [comment]
@matz-e 
"if OSG_LOCATION is not in the environment and the configuration variable is not set"
What does this mean?

**Comment by matz-e** [comment]
Updated my comment above to a list (: — also changed the location where the variable should be set.  The configuration is the right place for that, since we can crash/notify the user before starting.

In terms of python, I mean this: `if "OSG_LOCATION" in os.environ and os.environ["OSG_LOCATION"]`, which can be shortened to `if os.environ.get("OSG_LOCATION", "")`.

In terms of the shell: `OSG_LOCATION=` shows up in the output of `env` and has something behind the `=`.

**Comment by klannon** [comment]
Question:  Should we be parsing the contents of `OSG_LOCATION` to extract the OSG major (and minor?) versions and pass those on to the worker?  It seems like sending the full OSG_LOCATION value is bad because it's architecture specific and the worker and master don't have to share the same architecture, right?

**Comment by klannon** [comment]
OK, re-reading your original plan @matz-e you mention "shell magic" to extract the relevant pieces.  I think what we really want to do is just get the major and minor versions (i.e. `3.3/3.3.15`) from the OSG_LOCATION of the master, and pass that the the workers.  We should retain the part on the worker where we rely on CVMFS (i.e. the master might be running somewhere where OSG is installed manually instead of through CVMFS) and we should use the appropriate RH and architecture versions as currently determined in the script.  Let me know if you think that's the wrong approach.

**Comment by matz-e** [comment]
@klannon: agreed. @WenzhaoLi for this, I think it would be most dependable to approach the back of the path as the "fixed" structure part and parse/split from there.
