### ISSUE TITLE
Remove `units_paused` from reporting.

### ISSUE THREAD

**Issue by annawoodard** [matz-e/lobster#421]
`units_paused = units_failed + units_skipped`

Reporting `units_paused` places an unnecessary strain on the user to figure out a lobster-specific vocabulary word that is redundant, since we already report `units_failed` and `units_skipped` separately.

**Comment by matz-e** [comment]
May be a good idea to also add a small glossary to the monitoring page?

**Comment by matz-e** [comment]
There was one thing why I added `paused`. When running the MC chain, `units_paused` from the parent are added to the `units_paused` of the dependent workflows:
```
        parent_paused = self.db.execute("""
            select
                ifnull((
                    case when parent is not null
                    then
                        (select units_paused from workflows where workflows.id == wf.parent)
                    else 0
                    end
                ), 0)
            from workflows as wf where id == ?
            """, (id,)).fetchone()[0]

        self.db.execute("""
            update workflows set
                units_running=ifnull((select count(*) from units_{0} where status == 1), 0),
                units_done=ifnull((select count(*) from units_{0} where status in (2, 6, 7, 8)), 0),
                units_paused=ifnull((
                        select count(*)
                        from units_{0}
                        where
                            (failed > ? or file in (select id from files_{0} where skipped >= ?))
                            and status in (0, 3, 4)
                    ), 0) + ?
            where label=?""".format(label),
            (self.config.advanced.threshold_for_failure, self.config.advanced.threshold_for_skipping, parent_paused, label,)
        )
```
(from [here](https://github.com/matz-e/lobster/blob/master/lobster/core/unit.py#L595-L620))

Unless you have a better usage of terms, I'd rather leave this as it is (i.e. close this issue), and add a new one to have a glossary:

* **skipped** units in files that were in a failed task more than threshold times
* **failed** units in a task that failed more than threshold times
* **paused** all of the above + units whose parent files/units were skipped/failed

**Comment by matz-e** [comment]
IMO, this continues in #404.
