### ISSUE TITLE
Chirp Instructions Give Errors

### ISSUE THREAD

**Issue by klannon** [matz-e/lobster#430]
There are two issues with the Chirp instructions:

 1.  This line is only valid in `bash`: `echo "globus:$(voms-proxy-info -identity|sed 's/ /_/g') rwlda" >> /hadoop/store/user/$USER/.__acl`.  In `tcsh`  you need something like this (at least, it's what I used): `echo "globus:`voms-proxy-info -identity|sed 's/ /_/g'` rwlda" >> /hadoop/store/user/lannon/.__acl`  Would that work also in `bash`

 2.  The instructions suggest that as a test I create and delete a directory.  Creation works, but removal returns `couldn't rmdir: Permission denied`.

I can probably fix (1) on my own but it would be nice to know whether we can give a shell agnostic version of that statement.  For (2) I need to understand whether this is just not working for me because of some mistake I made, or whether there's a problem in the directions.

**Comment by khurtado** [comment]
It seems `rmdir` doesn't work because a new `.__acl` is created inside the `test` directory, so it is not empty anymore. I had to delete that file before being able to use `rmdir`. Should we add this extra line in the instructions  or change the test to just creating a file? 

```
[earth] ~ >chirp eddie.crc.nd.edu:9094 rmdir /store/user/khurtado/test11
couldn't rmdir: Permission denied
[earth] ~ >chirp eddie.crc.nd.edu:9094 rm /store/user/khurtado/test11/.__acl
[earth] ~ >chirp eddie.crc.nd.edu:9094 rmdir /store/user/khurtado/test11/
[earth] ~ 
```

**Comment by klannon** [comment]
That sounds like a good idea to me.

**Comment by klannon** [comment]
Let me see if I can do it now...

**Comment by klannon** [comment]
Note:  I checked that using backwards quotes instead of `$()` works in `bash` so I committed that change too.

**Comment by matz-e** [comment]
Hmpf. You can't nest backticks, that's why they came up with `$()`…

**Comment by klannon** [comment]
But it works here.  Is there a problem somewhere else?  Do you have an alternative solution.  Trust me, it's not fun for me to translate the instructions from `bash` to `tcsh` for each new user who tries to use this.

**Comment by khurtado** [comment]
Is there any particular reason new users are assigned a `tcsh` and not `bash` by the way?
The first thing I did when I got my account was `chsh -s /bin/bash` :)

If we don't want to use backticks, what about:
```
voms-proxy-info -identity | sed 's/ /_/g' | xargs echo -e "globus:\e" >> /hadoop/store/user/$USER/.__acl
```
?

**Comment by klannon** [comment]
The default shell is set by the CRC.  If you want to convince them to switch to `bash`, I won't stop you.

The above works for me, so if it's preferable for @matz-e, I have no objections.

**Comment by matz-e** [comment]
@khurtado I emailed support to switch the shell to `bash` (seems a US scientific computing particularity to have a preference for `tcsh`). I think the backticks are easiest, they are just what I would consider "bad practice" with POSIX shells by now… introducing the notion of `xargs` may not be bad though, either.

**Comment by khurtado** [comment]
> @khurtado I emailed support to switch the shell to bash (seems a US scientific computing particularity >to have a preference for tcsh).
Interesting....

> I think the backticks are easiest, they are just what I would consider "bad >practice" with POSIX shells >by now… introducing the notion of xargs may not be bad though, either.
Yeah, I agree this is bad practice for POSIX shells.  I guess the issue in this case is that `tcsh` is not precisely a fully POSIX-compliant shell :)
