### ISSUE TITLE
Factory Instructions Don't Work As Written in tcsh

### ISSUE THREAD

**Issue by klannon** [matz-e/lobster#431]
This: `nohup work_queue_factory -T condor -M lobster_$USER.* -o /tmp/${USER}_factory.debug -C examples/factory.json > /tmp/${USER}_factory.log &`

In `tcsh` needs quotes around `lobster_$USER.*` to keep the shell from trying to expand the wildcard.  Can I just add quotes without messing it up for `bash` users?

**Comment by matz-e** [comment]
Yes, please do. Of course, I think there's a bash option to have the behavior match tcsh.
