### ISSUE TITLE
Chirpd creates files as root

### ISSUE THREAD

**Issue by khurtado** [matz-e/lobster#432]
Since `chirpd` is run as root (although with  `-i xrootd` to supposedly downgrade privileges to a user), files written via this service have `root` ownership.

If the `xrootd` user is added to the `osgusers` and `hdfs` groups globally, we could strictly run `chirp` as that user.

In both cases (files written as `root` or `xrootd`) users are not able to delete files created by `chirp` via `fuse` though, you would need to use `chirp` itself for that. This is the same problem `gfal` has, those files are created  with `uscms01` ownership so you can't just `rm file` and need to depend on `gfal` or `globus-job-run` for that.

We could also run `chirpd` as `uscms01` and depend on the same permissions and ownership `gfal` has.

What would you prefer?

**Comment by klannon** [comment]
To me, `uscms01` makes more sense than `xrootd` since this really doesn't have anything to do with XRootD (unless I'm confused).

**Comment by khurtado** [comment]
Okay, that's what I was thinking too. I will make the change tomorrow.

**Comment by khurtado** [comment]
Ummhh... I just realized I used the word `xrootd` multiple times to refer to the user when I really wanted to write `chirp`. But anyway, still think reusing `uscms01:osgusers` is better than writing things like `root:root` or `chirp:chirp`.

**Comment by klannon** [comment]
I can understand why you'd have xrootd on the brain!  If we use `uscms01:osgusers` then we'd have the same ownership whether the files were staged out via chirp or srm, so sounds like we agree.

**Comment by khurtado** [comment]
Okay, it's done...
