### ISSUE TITLE
Log state of Lobster software

### ISSUE THREAD

**Issue by annawoodard** [matz-e/lobster#433]
It would be good to have a way to somehow log the state of the Lobster software-- preferably the hash of HEAD. It's hard to debug when that info is lost.

**Comment by matz-e** [comment]
Something akin to [this](http://logc.github.io/blog/2014/04/01/python-egg-tagged-with-git-commit-hash/)?

**Comment by annawoodard** [comment]
Yes, that's perfect!

**Comment by annawoodard** [comment]
On second thought, this should be straightforward...

**Comment by WenzhaoLi** [comment]
Do you think it's a good idea if I parse the `git log` to `dict` and store it somewhere? @annawoodard @matz-e

**Comment by matz-e** [comment]
The link above lists this:
```
GIT_HEAD_REV = check_output(shlex.split('git rev-parse --short HEAD')).strip()
```
I would not parse `git log` (¿to a `dict`? — not sure what you mean by that)…

**Comment by WenzhaoLi** [comment]
I tried this. It didn't work. 
I mean parse the output of `git log` and make it a `dict` in python.

**Comment by klannon** [comment]
Can you be more specific about what you tried and how it failed?

**Comment by WenzhaoLi** [comment]
I followed the instruction and tried installing the lobster.
```
(.lobster) [earth] ~/lobster >python setup.py install
  File "setup.py", line 59
    options = dict(egg_info = dict(tag_build = "dev_" + GIT_HEAD_REV)),
          ^
SyntaxError: invalid syntax
```

**Comment by matz-e** [comment]
You're missing a comma in the line before that (should read `},`), that's the first thing I'd check if I see a syntax error.

**Comment by WenzhaoLi** [comment]
OH! You got it!
It works now..

**Comment by WenzhaoLi** [comment]
How can I check the version after installation? 
I don't understand the instruction for this part..

**Comment by WenzhaoLi** [comment]
Do I need 'setup.cfg` this  file?

**Comment by matz-e** [comment]
We'd have to add a `lobster --version` command… If you start a new run, Lobster should save the version in the state file (`status.yaml` in the working directory):
```
earth: head -n 1 /tmpscratch/users/matze/ttH/v31/status.yaml
version: '1.5'
```

We don't need `setup.cfg` so far.

**Comment by matz-e** [comment]
Ultimately, all this may need some tuning to show the right version when running from a local installation as well as a directory checked out from source without running the install command.

**Comment by WenzhaoLi** [comment]
OK. I get it.
Can I add the `lobster --version` command?
It sounds fun.

**Comment by matz-e** [comment]
Sure, go for it!

**Comment by WenzhaoLi** [comment]
Where should I start? 
I am a newbie..

**Comment by matz-e** [comment]
* in `ui.py`, add a `--version` flag to the argument parser (may require reading the manual for `argparse`)
* find the bit of the code that registers the checkpoint `"version"` (grep for `register`)
* when `--version` is passed to Lobster, print the version and exit

**Comment by WenzhaoLi** [comment]
@matz-e 
Where is the code that registers the checkpoint "version"?  I couldn't find it.
After I locate that code, what should I do about it?

**Comment by klannon** [comment]
@WenzhaoLi: Did you follow @matz-e suggestion and `grep` in the code for the word `register`?

**Comment by WenzhaoLi** [comment]
@klannon Yes. I can find the `cms version` but can't find the `lobster version`.

**Comment by annawoodard** [comment]
We don't increment the Lobster version very systematically (or often). I would argue that a `--version` flag isn't all that useful. One thing that @klannon suggested was a `version` variant that would, in addition to versions, print the current HEAD hash and the one in `status.yaml` and a warning if they are different.

I personally think that we get 95% of the benefit with 10% of the work by just writing the HEAD hash to `status.yaml` and logging it, no need for anything fancy.

**Comment by klannon** [comment]
What about for users that don't install using the developer approach.  Do they have a way to get info about what version they're running right now?  I'm not opposed to implementing writing to `status.yaml` first and getting that deployed.  However, I think having the `--version` command will ultimately be useful as well.

For tracking, if you want to split this issue into the two sub-issues so that we can close the `status.yaml` one as soon as it's done, I'm fine with that.

**Comment by WenzhaoLi** [comment]
I will print hash to `status.yaml` and log it as soon as the job is done and close this issue. And I will keep doing the `--version` after that.

**Comment by annawoodard** [comment]
> log it as soon as the job is done

I don't quite follow. This should happen at the beginning of the run, no?

>  and close this issue

Sounds good! Can you open a new issue with the `--version` part?

**Comment by WenzhaoLi** [comment]
@annawoodard : Oh yeah. I mean the job I am running now. It's still merging.

**Comment by matz-e** [comment]
I think for this to work in all usage scenarios, it is important to put the setuptools glue in… so that the version hash is saved when Lobster is installed via `pip`.

Also, I think we should keep the version number and consistently use it for breaking changes.  If we rely on the hash for that, and insist that the hash remains unchanged, that will make it harder to work on fixes for Lobster (with restarts and so on), while intermittently committing work in progress.

So in the long run, I think we should have a version string like `2.1-a234fea-dirty` (the last part marking uncommitted in changes), where only the first part is checked and Lobster refuses to run due to incompatibilities.

**Comment by annawoodard** [comment]
@matz-e: Agreed!
@WenzhaoLi: So to break it down, you'll need to:

1) Change `version=1.5` in `setup.py` to something like this:
```
head = subprocess.check_output(shlex.split('git rev-parse --short HEAD')).strip()
diff = subprocess.check_output(shlex.split('git diff'))
status = 'dirty' if diff else 'clean'
version = '{major}-{head}-{status}'.format(major=1.5, head=head, status=status)
```

2) Modify the `verify` function in `util.py` to parse `my_version` to get the `major` identifier and only complain if that is different. (Try: `major, head, status = my_version.split('-')`)

3) Log the Lobster version (probably around where we log the WQ version-- search for "using wq from" in `process.py`).

**Comment by annawoodard** [comment]
Note the above will only properly log the _installed_ version and won't reflect what you're actually running if you are using `python lobster.py process config.py`. We'd like both to work. There's probably a more elegant way to figure out if you're running the installed version or using `python lobster.py process config.py` (@matz-e let us know if so), but one way would be to take advantage of the fact that the installed version path always looks something like this: `~/.lobster/lib/python2.7/site-packages/lobster`. So, to make sure you always get the version you're running with, you could do something like:
```
      if 'site-packages' in __file__:
          version = get_distribution('Lobster').version
      else:
          start = os.getcwd()
          os.chdir(os.path.dirname(__file__))
          head = subprocess.check_output(shlex.split('git rev-parse --short HEAD')).strip()
          diff = subprocess.check_output(shlex.split('git diff'))
          status = 'dirty' if diff else 'clean'
          os.chdir(start)
          version = '{major}-{head}-{status}'.format(major=1.5, head=head, status=status)
```

You could factor this into a function (say, stick it in `util.py`). Then use it to return the version in `setup.py` and instead of `get_distribution` when logging the version in `process.py`.

@WenzhaoLi: I'm not explaining all of the steps/code here: let us know if you want anything clarified.

**Comment by WenzhaoLi** [comment]
- os.chdir(os.path.dirname(__file__))
@annawoodard Why would you change the working directory there?

**Comment by annawoodard** [comment]
@WenzhaoLi: If you give the full path to `lobster.py`, you don't need to be in the git repo directory to run it. So you could run `python /path/to/lobster.py process config.py` from outside of the source directory. In that case the `git rev-parse --short HEAD` and `git diff` commands will fail. So in the example I had you switch to the repo directory and then switch back. There are probably reasons why this isn't a great idea, but it was the first thing that came to my mind-- someone else might have a more elegant idea.

**Comment by WenzhaoLi** [comment]
@annawoodard Got it! Sweet!
