### ISSUE TITLE
Log lobster PID

### ISSUE THREAD

**Issue by matz-e** [matz-e/lobster#441]
We should stuff the PID (**after** daemonizing) into the log to allow for quick cross-checks.  The PID is also in the lockfile, but that may not be available after Lobster crashes; So we should log it…

**Comment by annawoodard** [comment]
Agreed. This might be a good one for @WenzhaoLi?

**Comment by klannon** [comment]
Certainly.  @matz-e, can you outline the basic steps (including places where changes need to be made in code) for @WenzhaoLi to implement this?  The @WenzhaoLi can get started on it.

**Comment by annawoodard** [comment]
Note @WenzhaoLi: I vote you do #433 first, considering all the issues with lobster versions we've been having lately. Let us know if you get stuck on that one and we'll get you on track.

**Comment by matz-e** [comment]
For reference:

1. Find out how to obtain the PID in python (stackexchange may be your friend)
2. Log it for example [here](https://github.com/matz-e/lobster/blob/master/lobster/commands/process.py#L177)

(does this need more detail?)
