### ISSUE TITLE
Set minimum taskid

### ISSUE THREAD

**Issue by annawoodard** [matz-e/lobster#455]
See cooperative-computing-lab/cctools#1428.

We should use the new functionality to set the minimum ID in case Lobster is terminated and restarted. This will make debugging easier for @btovar because there won't be repeated task ids.

**Comment by annawoodard** [comment]
Might be a good one for @WenzhaoLi.

**Comment by WenzhaoLi** [comment]
I got this one!

**Comment by klannon** [comment]
OK, but we should keep in mind you start classes next week.  Maybe Thurs after the regular HEP-computing meeting those of us who are available could sit down and assess the task assignments and make sure we have a sensible plan in light of the start of the semester. 😱

**Comment by WenzhaoLi** [comment]
@annawoodard Could you point me to the place to start this one?

**Comment by annawoodard** [comment]
You're on a roll with the issue closing lately! Go @WenzhaoLi! 👏 👏 👏 

There are various possibilities, but here's the first that comes to mind...

First you need to know what the minimum taskid should be. If the master is starting for the first time, it should be 1. If it's restarting, it should be one more than the last task id used (so the maximum existing taskid + 1). I would recommend pulling that from the `tasks` table in the DB. Everything that deals with the DB should be in `unit.py`. 

So you could try:

1. Make a `UnitStore` method there that returns something like [1]:
    ```
    db.execute('select ifnull(max(id), 0) from tasks').fetchone()[0]
    ```

2. Make a `TaskProvider.max_taskid` (see `source.py`) method that calls the method from 1 and passes it up (search for `def done` in `source.py` for an example of a method that does something similar).

3. In `process.py`, add something like [2]
    ```
    id = task_src.max_taskid() + 1
    self.queue.specify_min_taskid(id)
    ```
somewhere soon after we create the queue (search for `self.queue = wq.WorkQueue(-1)`).

[1] Keep in mind that `fetchone` returns a tuple, which is why I'm taking the first element-- you can read more about it in the sqlite3 module documentation.
[2] To find out what the WQ binding we need to use is, I clicked on "files changed" in the cctools PR [above](https://github.com/cooperative-computing-lab/cctools/pull/1428/commits/bc2d469a16c15510dcf442f606263a01c751fc62) and see that in `work_queue/src/python/work_queue.binding.py` @btovar added `specify_min_taskid`.
