### ISSUE TITLE
Improve CVMFS robustness

### ISSUE THREAD

**Issue by klannon** [matz-e/lobster#458]
We need to modify our CERN CVMFS configuration to make it more robust against failures at FNAL.  See: https://github.com/matz-e/lobster/blob/57ede54006b73e9f52e10c3d38ad843f0920647a/lobster/core/data/wrapper.sh#L89-L91

We should add the BNL option that is also used for the OSG repo to the `*.cern.ch` one.

(Thanks to @khurtado for figuring this out!)

**Comment by annawoodard** [comment]
I'm running now so I'll test
