### ISSUE TITLE
Stagein and Startup times messed up in plots

### ISSUE THREAD

**Issue by klannon** [matz-e/lobster#46]
See http://www.crc.nd.edu/~cmuelle2/bean_attempt2_part3_cron/

Five out of six entries in plot have stage-in time set to ~ -2e7.  Likewise, five out of six entries in startup have time set to ~ 2e7.  These values probably cancel each other in the accounting, but I believe they cause problems with the detailed pie chart, as well as the histograms and profile plotting.

**Comment by annawoodard** [comment]
This has been fixed, with Ben Tovar's help.
