### ISSUE TITLE
Classic and ELK Worker Plot Disagree

### ISSUE THREAD

**Issue by klannon** [matz-e/lobster#460]
Classic plotting:
![workers-plot](https://cloud.githubusercontent.com/assets/5149849/17832890/abb80192-66dc-11e6-8754-487d74e221d7.png)

ELK:
<img width="663" alt="untitled" src="https://cloud.githubusercontent.com/assets/5149849/17832902/17752e96-66dd-11e6-8737-fb9677770e8c.png">

Notice "busy" ~ "able" in classic but not in ELK.

**Comment by annawoodard** [comment]
I can confirm I'm seeing this, too...
