### ISSUE TITLE
Add parameter scans for MC generation

### ISSUE THREAD

**Issue by annawoodard** [matz-e/lobster#461]
When doing scans over a given parameter space in MC generation, it is necessary to run over a set of input gridpacks. It would be convenient if this could be done within a single workflow by scanning the gridpacks, rather than as one workflow per gridpack.

See [here](https://indico.cern.ch/event/517162/contributions/2139828/attachments/1261731/1865231/susyscan-Apr21-2016.pdf) for a discussion of the status of this issue CMS-wide.

**Comment by klannon** [comment]
If I understand the CMS-wide approach, the advantage is that it's handled completely within CMSSW, meaning that no special hooks or behavior are required from the workflow management tool (CRAB, Lobster, WMAgent).  This seems desirable.

**Comment by annawoodard** [comment]
I agree, but as far as I understand, the completely-within-CMSSW approach isn't completely functional yet. Or did I miss that?

I've just implemented the gridpack scanning approach for Lobster, so I think it makes sense to merge in.

**Comment by annawoodard** [comment]
(unless I'm mistaken and the CMS-wide approach is ready to go)

**Comment by annawoodard** [comment]
(point is, I need a way to accomplish this now :smile:)

**Comment by klannon** [comment]
Definitely make it work for you the quickest way!  I guess I'm think more for sustainability.  The fewer special processing modes we have to carry around forever, the less complicated it will be in the long run.

I don't know if Josh's thing is ready.  The slides you reference are the ones from back in April.  I hope some progress has been made.  It was needed urgently already back then.  I thought the plan was to run it for ICHEP.

**Comment by matz-e** [comment]
This looks pretty sustainable to me? We could go a bit of an extra mile, and make the datasets all self-contained packages for easier future maintenance. I feel like we might re-shuffle a couple of things to achieve this. Need to stare at more code, though…

**Comment by klannon** [comment]
I should stress that my sustainability concern is completely independent 
of the implementation.  It's just that if we've got special purpose 
running modes that are only used once every few months to few years, 
they will always be broken.  At least, based on my observations so far.  
We tend to implement changes and test with 1-2 modes (ntupling and MC 
production).  It's hard to think of an easy way to avoid, other than 
being judicious with introducing new modes.

**Comment by annawoodard** [comment]
@klannon: I'm completely in agreement that we ought to try to keep Lobster lean. On the other hand, I want to graduate as soon as possible. Can you help me determine the state of the CMS-wide implementation of this? If it is already functional then I'll go ahead and switch my workflow over now and close the PR. Otherwise, I can open an issue to remind us to drop this functionality when the CMS-wide implementation is ready.

**Comment by klannon** [comment]
No, I'm not going to help you, because this will be a problem for 
someone else, I think.  :)  If you would be so kind as to open the issue 
to remind us that this feature (presumably) has a finite lifetime, that 
would be awesome.  Then just press on.  (And for future reference, if it 
ever sounds like I'm suggesting something that would slow down your 
graduation, it either means that (a) I'm being stupid or (b) you've 
misunderstood me.  Listed in order of probability...)

**Comment by matz-e** [comment]
Sounds like we have a go?
