### ISSUE TITLE
Confirm file transfer after jobs?

### ISSUE THREAD

**Issue by annawoodard** [matz-e/lobster#47]
Charlie tried merging the datasets here:
/tmpscratch/users/cmuelle2/lobster_BNprod_v2p1/

There is one job in that processing run that the database thinks finished successfully, but we actually don't have the output for:

    sqlite> select status from jobs where id=7433;
    2

    $ls /hadoop/users/cmuelle2/lobster_BNprod_v2/DoubleElectron_2012B/merged_bean_7433.root
    ls: /hadoop/users/cmuelle2/lobster_BNprod_v2/DoubleElectron_2012B/merged_bean_7433.root: No such file or directory

I don't know how we can get an exit 0 from chirp and be missing the output file, but whatever the reason, we need to make sure that we don't lose any output files-- and if we do, we need to mark those jobits as unfinished.  Thoughts on the best time to do this check, @matz-e?

**Comment by matz-e** [comment]
Any opinions on closing this?  Does everyone think we're dealing with this now?

**Comment by matz-e** [comment]
Anyone?  Closing in 3… 2… 1…
