### ISSUE TITLE
Configure Fails if Config Doesn't Validate

### ISSUE THREAD

**Issue by klannon** [matz-e/lobster#474]
I am having an issue where I want to restart a run that was paused, but I can't because the Chirp server I was using is down.  I thought I could fix this with `lobster configure` but it won't let me because...you guessed it!  The chirp server is down so it fails the "validate" step and won't run configure.  This doesn't make sense to me.  Am I missing a reason why this is a good idea?

**Comment by matz-e** [comment]
Ah… we validate before the code branches out to run the sub-command. I think we can switch that to validate only when we create a new run.

**Comment by matz-e** [comment]
Well, turns out that this is a "feature" in our chirp wrapper…

**Comment by matz-e** [comment]
OK, here are some more thoughts: Did you call `lobster configure` with your original configuration file as an argument? If that is the case, we load the configuration that you pass Lobster, then check if the working directory is present and then execute the command you specify (`configure`).

Now the problem may be that we load the original configuration, which includes a `chirp://` line, and construct the `StorageConfiguration` in the process — which tries to create a `Chirp` object, that in turn [checks the connection to the chirp server and fails](https://github.com/matz-e/lobster/blob/master/lobster/se.py#L606).

Does this happen if you pass the working directory to the Lobster command? That would IMHO the preferred method, too. Maybe we should make this explicit in the documentation? Or mention it as a caveat?

**Comment by matz-e** [comment]
Confirmed that using the working directory directly works…

**Comment by klannon** [comment]
Thanks for sorting that out and improving the docs.

**Comment by matz-e** [comment]
I hope this is sufficient for you. I think that the energy it takes to work around this is better vested elsewhere.

**Comment by klannon** [comment]
Definitely.
