### ISSUE TITLE
Workflow-engine-like conditional processing

### ISSUE THREAD

**Issue by annawoodard** [matz-e/lobster#48]
Maybe this is going in the wrong direction, but we might consider adding some workflow-engine-like conditional processing functions, so that tasks would only start upon completion of some required task.  For example:

    tasks:
      - {label: dataset1}
      - {label: dataset2}
      - {label: dataset3, requires: dataset1}

**Comment by matz-e** [comment]
Having talked with @klannon about using multiple steps in one task, here's some more food for thought.  I think you (@annawoodard) have implemented some of this in custom wrappers?

* Generating millions of MC events produces lots of data
* Happens in two steps (GEN-SIM + RECO/MINIAODSIM)
* Intermediate data could be thrown away to reduce burden on storage element
* Requires individual wrappers currently
* Multi-step setup like in production sounds even more cumbersome

Taking what you suggested a notch further, it seems like we could handle this fairly easy (in theory [famous last words]) by having continuous conditional processing, were workflows get started without previous workflows finishing and get updated continuously.  This would look similar to a merge task (which then would basically be a step in this possible chain of workflows.)

Of course, handling this in plain SQL will be a mess…

**Comment by matz-e** [comment]
Another different thought: we could have a callback - every time a job finishes, it could append a new file with associated units into a dependent input dataset.
