### ISSUE TITLE
Disentangle inefficiencies in monitoring

### ISSUE THREAD

**Issue by annawoodard** [matz-e/lobster#484]
In the current Executable CPU / wall time histogram is calculated as
```
                 efficiency = tasks['time_cpu'] / (1. * tasks['cores'] * (tasks['time_processing_end'] - tasks['time_prologue_end']))                                                                                   
```

This makes it difficult to disentangle inefficiencies caused by the task waiting for data to stream from inefficiencies caused by a mismatch between cores the job is asking for and using. We should consider including both this and a version not divided by cores in the monitoring.

**Comment by annawoodard** [comment]
Nevermind!

I was getting `cores` and `allocated_cores` mixed up. Thanks @matz-e.

**Comment by matz-e** [comment]
Ah, OK. I was just going to mention that I was confused about this (but it's late, and we just had a neighbour's dog howl at a hedgehog in our backyard.)

**Comment by annawoodard** [comment]
He probably doesn't want to end up like this guy:
![dog-attacked01](https://cloud.githubusercontent.com/assets/5114833/18327315/f9a2ee96-7517-11e6-950d-4845e49d070c.jpg)

**Comment by matz-e** [comment]
Luckily he didn't. We returned him safely to his home (the dog) :)
