### ISSUE TITLE
Add task resources utilized for exhausted tasks to monitoring

### ISSUE THREAD

**Issue by annawoodard** [matz-e/lobster#504]
We currently have a whole class of tasks that may fail due to exhausted resources, but we never know what the distribution of resources they used was (are there many tasks that use just slightly above what is allocated, or maybe there's just one task that uses 10x the resources of normal ones?)

**Comment by klannon** [comment]
Wait, just thinking about this some more.  Won't the tasks always use whatever the limit is if they fail for exhausted resources?  (In other words, if you have tasks that fail because they exceed the 2 GB memory limit, won't the memory usage for all of them just be 2 GB or very close to it?

**Comment by annawoodard** [comment]
Ah, good point.
