### ISSUE TITLE
Hadd merging broken

### ISSUE THREAD

**Issue by matz-e** [matz-e/lobster#505]
From the slack:
```
cmuelle2 [16:59]  
Hi all, I noticed my merge tasks taking a while (days). In particular the log file below seems to indicate a command with spaces in the command line

[16:59]  
plots: http://www.crc.nd.edu/~cmuelle2/lobster/test__v0/

[17:00]  
log file: http://www.crc.nd.edu/~cmuelle2/lobster/test__v0/logs/33463.log
```

**Comment by annawoodard** [comment]
As @matz-e pointed out, it is likely that this is due to a limit on the number of shell arguments.

**Comment by klannon** [comment]
As I see it, there are basically only two options:
 1.  Refuse to merge more than some upper limit number of files.  This would be, I think, fairly easy to implement but would result in the final merged files not reaching the desired size target.
 2. Merge the files in batches of "N" where N is the maximum number of files that's safe to merge.  Then merge the batches.  The big downside I can see to this approach is that it makes merging more of a special case operation while as I understand, right now, it's just an application of Lobster's capability to run any command.  (Unless of course we create an intelligent merging script and make that the command.)

Any preference?  Am I missing an option?

**Comment by matz-e** [comment]
I'm actually preferring (2), because we can *merge more than one input file* that way.  That would solve #377, which I would enjoy for my analysis.

**Comment by matz-e** [comment]
As a side note, this may simplify how we handle merging on the master, since the EDM and the ROOT cases would get handled by one script?

**Comment by matz-e** [comment]
Since we got around @muell149 current limitation, can we close this and keep track of the outstanding changes in #377?
