### ISSUE TITLE
Another Time Accounting Bug...

### ISSUE THREAD

**Issue by klannon** [matz-e/lobster#510]
This seems similar to #280.  I'm seeing times that are effectively +/- infinity (and that add to give ~0):

![good-stage-in-hist](https://cloud.githubusercontent.com/assets/5149849/19570682/0f7ad51c-96c9-11e6-8f80-f6af5eb2f9b3.png)

![good-prologue-hist](https://cloud.githubusercontent.com/assets/5149849/19570687/136e0a04-96c9-11e6-8ee8-b885e732d2ff.png)

This is with `cctools-133-bcc1ac1d-cvmfs-40cf5bba` and `"version": "1.5-9f41635-clean"`.

**Comment by matz-e** [comment]
Let me guess, LHEGS step? Found the bug… merits a facepalm emoticon, which @github is still missing.
