### ISSUE TITLE
process.err is getting filled with log messages.

### ISSUE THREAD

**Issue by matz-e** [matz-e/lobster#516]
That should not happen!

**Comment by klannon** [comment]
Details?

**Comment by matz-e** [comment]
The logging output from `process.log` also seems to show up in `process.err`, minus the formatting, thus duplicating all information when following Lobster progress like this:
```shell
tail -f process{.err,_debug.log}
```

**Comment by klannon** [comment]
Huh, I'd not noticed that before.  I'll check once I get my next project 
started to confirm I get that too.

**Comment by matz-e** [comment]
Must have been something temporary in the setup. Currently not seeing this anymore.
