### ISSUE TITLE
Parrot cache task specific?

### ISSUE THREAD

**Issue by matz-e** [matz-e/lobster#517]
I see this on the worker currently:
```shell
d12chas109: du -hs cache
39M	cache
d12chas109: du -hs t.839/cctools-temp-t.839.DPqpnx/*
1.9G	t.839/cctools-temp-t.839.DPqpnx/parrot.187567
8.6M	t.839/cctools-temp-t.839.DPqpnx/tmpSAK_CQ
```
which seems to indicate to me that the parrot cache is currently not shared. Is this desired? Did I miss some transition there?

**Comment by klannon** [comment]
Nothing intentional, at least that I'm aware of.  Do we control this in Lobster or does WQ take care of it?

**Comment by matz-e** [comment]
We control it somewhat currently, I can ping @btovar next week when he's back about which specific variables to use.

Currently, in [`task.py`](https://github.com/matz-e/lobster/blob/master/lobster/core/data/wrapper.sh#L94):
```shell
export PARROT_CACHE=${WORKER_TMPDIR:-${TMPDIR:-.}}
```
I thought that this should use a cache global to the *worker*, not the *task*.

**Comment by btovar** [comment]
TMPDIR is set per task so that tasks do not clobber each other. Thus, if you are not setting WORKER_TMPDIR, each tasks gets a different PARROT_CACHE.

**Comment by matz-e** [comment]
So… we actually use the worker cache:
```shell
d8civy100: du -hs worker-187567-31496/cache/tmp/*
26M	worker-187567-31496/cache/tmp/ex_parrot_mwolf3
4.0K	worker-187567-31496/cache/tmp/hot_cache
```
But it looks like at least CVMFS does use `TMPDIR`:
```
d8civy100: du -hs worker-187567-31496/t.17201/cctools-temp-t.17201.0CkwcY/parrot.187567/*
871M	worker-187567-31496/t.17201/cctools-temp-t.17201.0CkwcY/parrot.187567/cvmfs
```

@btovar is there a separate setting for steering the CVMFS cache?

**Comment by btovar** [comment]
There is:

export PARROT_CVMFS_ALIEN_CACHE="..."

**Comment by matz-e** [comment]
Isn't that deprecated? Or is that just the command line option to parrot?

**Comment by btovar** [comment]
I believe it is only the command line. (Unless there are some news I missed in the last days.)

**Comment by matz-e** [comment]
OK, thanks! Wasn't sure how to read that in the parrot help. The deprecated seems to point to the command line option, but could have also been for the environment variable.

**Comment by btovar** [comment]
I think Tim wants to move everything to --cvmfs-option-file. But there are many places that depend on the environment variables.

**Comment by matz-e** [comment]
Would it be sensible then to set it to`$PARROT_CACHE/cvmfs` for now?

**Comment by btovar** [comment]
Yes, that should work. Just remember that if PARROT_CACHE is not set, it falls back to TMPDIR.
