### ISSUE TITLE
Release creation needs SCRAM_ARCH set right in some setups

### ISSUE THREAD

**Issue by matz-e** [matz-e/lobster#547]
Action plan:

1. Use full `SCRAM_ARCH` instead of just the SLC release when packing
2. Extract `SCRAM_ARCH` on the worker from sandbox name and use it

**Comment by matz-e** [comment]
Alternative: find out why scram does not switch `SCRAM_ARCH` automatically…

**Comment by klannon** [comment]
Hypothesis: Looking quickly at the condor submit file WQ makes for the factory, it looks like it has `getenv = True`, which means that it would pass on the SCRAM_ARCH from the shell where the factory was started.  (This is assuming you're debugging the problem Charlie found where he launched a factory with the CMSSW environment setup and it gave him the wrong SCRAM_ARCH...)

**Comment by matz-e** [comment]
It should have been the right one with the `cmsenv`, since it's the same release. But even without the `cmsenv`, things did not work for him. Interactively, `scram` just picks the right arch and creates the release, but not on condor. I've compared environments from one of my tasks with his, and haven't spotted anything obvious…
