### ISSUE TITLE
Clarify "Paused," "Failed," and "Skipped"

### ISSUE THREAD

**Issue by klannon** [matz-e/lobster#557]
On the Lobster monitoring: I have no idea what these numbers mean (other than that they're units that didn't get processed for some reason).  If the distinctions are important, I think we need to document what those categories are, either in the Lobster documentation, or by writing the definitions write on the monitoring webpage.  This had better get done before @annawoodard and @matz-e gradate or I'm coming to your defenses and asking it as a question!  😄

**Comment by annawoodard** [comment]
> I'm coming to your defenses and asking it as a question! 

You being my advisor, I hope you come to my defense anyways....

I propose we add the definitions as tooltips that you see if you hover over the table heading. That way it doesn't make things too busy. When possible I prefer not to rely on the user to read the documentation :smile:

**Comment by matz-e** [comment]
Yes, tooltips sound like a good idea. Ideally with some markup to hint that there is more of an explanation to be had, too.

**Comment by annawoodard** [comment]
I can take a stab at this.
