### ISSUE TITLE
estimate disk and memory usage

### ISSUE THREAD

**Issue by annawoodard** [matz-e/lobster#57]
Currently, the user starts their master, then submits jobs.  We should implement a pilot job (or, more simply, just read out this info from the first returning job) which reports back the estimated disk and memory usage, then update the suggested condor_submit command.  Of course this will just be an estimate-- I think that's ok.

**Comment by matz-e** [comment]
Doing some grave-digging here… wouldn't this be somewhat solved with the newest WQ auto-labeling of categories? It doesn't rely on a test job and may require passing high first estimates to Lobster, but after WQ adjusts resources, we get all the benefits with no work from our side.

W.r.t. test tasks, I don't think we really need them. We normally process such large amounts of data over longer times that we can just adjust on the fly. CRAB, on the other hand, fixes everything at the beginning, and without test jobs, things go downhill really fast.

**Comment by annawoodard** [comment]
> Doing some grave-digging here… wouldn't this be somewhat solved with the newest WQ auto-labeling of categories? It doesn't rely on a test job and may require passing high first estimates to Lobster, but after WQ adjusts resources, we get all the benefits with no work from our side.

Agreed.

> W.r.t. test tasks, I don't think we really need them. We normally process such large amounts of data over longer times that we can just adjust on the fly. CRAB, on the other hand, fixes everything at the beginning, and without test jobs, things go downhill really fast.

Agreed again.

I move to close the issue until we find a case where auto-labeling of categories isn't sufficient.

**Comment by matz-e** [comment]
Thanks for the input! Closing then…

**Comment by klannon** [comment]
Two comments/questions:
1.  Have we checked that the WQ auto-adjustments are working and make sense?  It would be nice to see some confirmation of this.
2.  Adjusting on the fly:  Can this be done by non-experts or does it require editing the DB directly?  Can it be done without shutting Lobster down and restarting?  (I guess there's already an issue for that...)

Doh!  You closed the issue while I was still commenting.  Well, I don't disagree with closing this, but there might still be a few loose ends.  My 2nd point is probably part of a different issue.  Has my first point already been addressed?

**Comment by matz-e** [comment]
Good points. We need to check with @btovar about (1), with your run, preferably. And (2) has the sync issues that are open. Besides, aren't we working towards a Lobster-system where Lobster figures out what the right values should be?

**Comment by klannon** [comment]
Certainly, but I'm becoming convinced that the right sequence there is to put in the knobs that make it easy for a user to make adjustments manually and then later teach a computer how to do it automatically.  It's a lot easier for a person to recognize the need to adjust something (like the example of hitting a bandwidth bottleneck) that to develop an algorithm for it.

**Comment by btovar** [comment]
About that, do you have the logs to check that auto-labeling is working correctly?

**Comment by klannon** [comment]
I hope so.  All of the logs for that job are on earth here:

/tmpscratch/users/klannon/mcprod_ttZ_v1/

I see there is a "work_queue_monitoring" directory there.  Is that what 
you need?
