### ISSUE TITLE
Improve error message when `report.json` is not produced

### ISSUE THREAD

**Issue by annawoodard** [matz-e/lobster#617]
As reported by @Andrew42.

This error message is confusing:
```
[ERROR] lobster.cmssw.taskhandler: error processing 1132:
[Errno 2] No such file or directory: '/tmpscratch/users/awightma/lobster_test_20171102/zoom_pass_1_c2B/running/0000/1132/report.json'
```
Later in the log file we report that 1132 failed due to an 'unclassified error'. But as-is, it makes the missing 'report.json' sound like the cause of the error, and not the effect (the task failed before producing it). We should clarify this.

**Comment by matz-e** [comment]
Agreed! Maybe we can supply a default `report.json` (empty or with the bare necessary content)? To make the machinery happy and not rely on some exit-code special case mapping?

**Comment by annawoodard** [comment]
Sounds good to me!
