### ISSUE TITLE
When using the HDFS backend, the chirp prefix != the stageout directory

### ISSUE THREAD

**Issue by annawoodard** [matz-e/lobster#70]
When using the HDFS chirp server backend, the leading 'hadoop' needs to be removed from the input file path. We can't just remove it in general, because a user could stageout to hadoop using the fuse-based backend. It's not very elegant, but the first approach that comes to mind is to add fields to the configuration file: in addition to 'stageout directory' and 'chirp server', add 'chirp stage in prefix' and 'chirp stageout prefix' (which could default to stageout directory). This would also fix #33, because we could use the chirp stage in prefix as a switch on whether or not to transfer inputs for local file-based jobs (that way we can allow for users that want to have WQ stage in, Chirp stage out, and also users that want Chirp stage in, Chirp stage out.)

**Comment by matz-e** [comment]
I'm a bit confused.  Doesn't the leading `/hadoop` only need to be removed when starting the chirp server?  I guess your pointing to our previous conversation about different directories for stage-in and stage-out?

Would this then lead to e.g.:
```
stageout directory: /hadoop/user/fsm/lobster/out
chirp server: earth.crc.nd.edu:3147
chirp stageout prefix: lobster/out
chirp stagein prefix: inputs
```
and the chirp server would have to be started with
```
chirp_server --root=user/fsm/ …
```
and then the inputs could be located in `/hadoop/user/fsm/inputs`, which would nicely separate them from the outputs?

As an alternative, maybe we could just have the user specify a chirp root, where the difference between the `chirp root` and the `stageout directory` will automatically get prepended to the output filenames by lobster.  Then the input file transfer mechanism as it is could handle the same requirements?  As in:
```
stageout directory: /hadoop/user/fsm/lobster/out
chirp server: earth.crc.nd.edu:3147
chirp root: /hadoop/user/fsm
```
and then the job handler adds `lobster/out` to the file output paths?  Just wondering…

**Comment by annawoodard** [comment]
I like your idea of a chirp root instead-- I think that's clearer. I guess
in that case, we can check if each input file starts with the chirp root,
and use that as the switch on whether or not to transfer input files? (I
think the only case in which someone would want to use WQ for stagein and
Chirp for stageout is if the input files were not actually in a place
accessible to the Chirp server, i.e on a different filesystem.)

**Comment by matz-e** [comment]
Yes, exactly.  I think that it keeps the number of parameters down a little bit, and I think the changes that would have to be made to accomplish this are minimal.

WQ for stage-in, I think, should be an absolute emergency situation, maybe?

**Comment by annawoodard** [comment]
I agree, it should be for emergencies. But it won't be hard to support it,
so we might as well.
