### ISSUE TITLE
Improve Dashboard Monitoring

### ISSUE THREAD

**Issue by klannon** [matz-e/lobster#72]
Something appears to have changed in Lobster's interaction with the dashboard such that the full information is not appearing there any more.  In particular, we seem to have lost information about running jobs as well as about CPU used.  See the following links for examples:

Recent run where it wasn't working:  (Charlie's run, I think):
http://dashb-cms-jobsmry.cern.ch/dashboard/request.py/dailysummary#button=jobstatus&sites%5B%5D=T3_US_NotreDame&sitesSort=3&start=2015-01-16&end=2015-01-18&timerange=daily&granularity=Hourly&generic=0&sortby=0&series=All

http://dashb-cms-jobsmry.cern.ch/dashboard/request.py/dailysummary#button=cpuconsumption&sites%5B%5D=T3_US_NotreDame&sitesSort=3&start=2015-01-16&end=2015-01-18&timerange=daily&granularity=Hourly&generic=0&sortby=0&series=All

Past run that worked fine (or at least the plots aren't empty):
http://dashb-cms-jobsmry.cern.ch/dashboard/request.py/dailysummary#button=jobstatus&sites%5B%5D=T3_US_NotreDame&sitesSort=3&start=2014-08-16&end=2015-01-20&timerange=daily&granularity=Daily&generic=0&sortby=0&series=All

http://dashb-cms-jobsmry.cern.ch/dashboard/request.py/dailysummary#button=cpuconsumption&sites%5B%5D=T3_US_NotreDame&sitesSort=3&start=2014-08-16&end=2015-01-20&timerange=daily&granularity=Daily&generic=0&sortby=0&series=All

Matthias: I've assigned you, but I think if we can move this to Kenyi, that would be good.

**Comment by annawoodard** [comment]
Awesome!
