### ISSUE TITLE
Remove Iteration from Merging

### ISSUE THREAD

**Issue by klannon** [matz-e/lobster#73]
As discussed this morning (Matthias, Mike, Kenyi and I), we are going to remove iteration from the merging.  The game plan is:

1.  Immediately change the code so that it never tries to merge.
2.  Implement a tool or utility that estimates the size of the data in the file without overhead.  See note below.
3.  Track the non-overhead data size of each file in lobster (presumably one of these databases you guys use).
4.  Implement some logic to group files for merging based on the new non-overhead file size estimate to hit the desired target, taking care not to be so exacting that the process becomes overly complicated.  In other words, if the user wants 3.5 GB files, it's probably fine to be anywhere between 3 GB and 4 GB, I would think).

The plan is that Matthias will do step 1 quickly, and then Kenyi will work on the rest, with Anna helping to show him around the relevant parts of the code.

Assuming this works, it should eliminate, or at least dramatically reduce, the long tail from interleaved merging, which I think is essential for the usability of Lobster in v1.

Note on file size estimates:

* This might be obvious to everyone, but in case it's not, care should be taken to estimate the *compressed* size of the data (i.e. not overhead) within the file.  The technique we discussed in the meeting was to use the standard CMS utility edmEventSize.  However, someone (Kenyi) should check that the sizes returned by that are the compressed size.  (This can probably be done empirically by making sure the total size--ignoring overhead--estimated by this approach is less by the appropriate amount that the file size reported for the event.)

* It's probably also worthwhile just to check the I/O statistics reported by CMSSW in the framework job report (fjr) to see if the numbers we need are already provided by cmsRun during the job (saving us the overhead of extracting it ourselves).  It might be necessary to do some investigation to verify whether any promising numbers can indeed be mapped back to the quantities we're interested in, but if they're in there, it would definitely be worth getting them from there.

**Comment by matz-e** [comment]
I've implemented a non-iterative version of the merging.  I'm testing it right now, first merge jobs have been successful, and I'll fix up anything that still comes up.

**Comment by matz-e** [comment]
Short FYI: this will make it harder to change the merge size while running (or, properly, restarting) lobster.  As in, if I change the merging file size from 0.5 Gb to 3.5 Gb, all the 0.5 Gb merge files are not going to get re-merged.  Should we just accept this limitation?  I think I would also have a solution to get around that.

**Comment by klannon** [comment]
For me, the right solution to this would be to have an option to trigger 
explicitly a remerge.  In other words, rather than having it as a 
side-effect of iterative merging, it would only happen if the current 
merging is manually stopped and then explicitly restarted. Ideally it 
should know to combine previously merged files and also 
as-of-yet-unmerged ones (without duplicating any events).

**Comment by annawoodard** [comment]
I think we should accept this limitation.

**Comment by khurtado** [comment]
Just committed some code related to items 2,3,4...

**Comment by matz-e** [comment]
Good!  I think I just learned another thing about these obscure ROOT settings.  Also kudos for catching non-existing event trees (we should be able to run jobs that produce non-EDM output).

BTW, in line with PEP-8, could you set your indentation to 4 spaces for our python code?  I think I see some code indented with only 2 spaces in there.

Also, I think we should automatically select your event size when merging (as in: if event size > 0, use it, otherwise use the full output size), but that's more polishing than anything else.

Thanks!

**Comment by khurtado** [comment]
Thanks for noticing Matthias! 
That reminds me to update my shiftwidth vim settings (or use vim 7.4+ with python-mode)

**Comment by matz-e** [comment]
Sorry to be so pedantic, but I hate to run into some issues with that later.

If you don't want to have all your python code look like that, you could set shiftwidht and tabstop conditional, I even do that for directories, like so:

    autocmd FileType python setlocal ts=4 sw=4 expandtab
    autocmd FileType ruby setlocal ts=2 sw=2 expandtab
    autocmd FileType tex  setlocal ts=2 sw=2 expandtab tw=70 formatoptions+=t iskeyword+=:
    autocmd FileType text setlocal textwidth=72

    autocmd BufNewFile,BufRead *.ldg,*.ledger setf ledger | comp ledger | setlocal ts=4 sw=4 expandtab
    autocmd BufNewFile,BufRead */CMSSW*{cc,h} setlocal ts=3 sw=3 expandtab
    autocmd BufNewFile,BufRead */nidra*{cc,h} setlocal ts=4 sw=4 expandtab
    autocmd BufNewFile,BufRead */Roast*{cc,h} setlocal ts=4 sw=4 expandtab

**Comment by khurtado** [comment]
Thanks Matthias... I used to use the vim-python-pep8-indent with filetypes support on with my own local compiled vim version, but realized I just used the standard vim on crc/earth machines instead for this. I will steal your settings for vim 7.2.
