### ISSUE TITLE
Adjust job sizes automatically

### ISSUE THREAD

**Issue by matz-e** [matz-e/lobster#74]
Since we have all the information needed in the database, we should be able to fine-tune the job size on the fly, i.e.:

1. Wait until ~100 jobs are completed
2. Get average runtime per luminosity section (or event) (time from 1st event - end of `cmsRun`)
3. Scale job size in luminosity sections to some target runtime, e.g., 30 minutes of processing

In conjunction with #65, this should allow us to target specific running times easily.

**Comment by klannon** [comment]
I was just talking with Anna about this on Friday.  The run time is just part of what we need to make this work as you'd want it to.  We should also get the followings:
* Average overhead per job, so we can account for the penalty of making jobs too small.
* Mean time to eviction (or evictions per hour, etc.):  Some way to account for the eviction probability.

The above two pieces of information would let you calculate what your target run time should be, while #65 plus this suggestion would let you figure out how to achieve that target run time.

I think Lobster already has everything it needs to calculate the overhead, but we need to get better information from WorkQueue on evictions to fill in that piece.

**Comment by annawoodard** [comment]
I agree with everything that's been said, but as far as how we should
prioritize this piece over other issues-- we should keep in mind that I
think at this point I think we have the most to gain in terms of efficiency
by getting our startup times under control.

**Comment by klannon** [comment]
Absolutely!  Mostly, I think this is just good to write down because I 
feel like we've gone from having a vague idea that Lobster should be 
dynamic to having a specific (and apparently do-able) plan for making 
this happen.

**Comment by matz-e** [comment]
Yes, keeping some blueprints of all this around should come in handy later, when we can actually fill in these bits.  I don't think any of this is up for immediate action, too.
