### ISSUE TITLE
Proper license?

### ISSUE THREAD

**Issue by matz-e** [matz-e/lobster#75]
This code is essentially proprietary, since we don't specify any license at all.  I think it would be helpful, just so that conditions are clear in case other people want to use lobster.  CRAB 3 (the client) says it uses [some OSI approved license][1].  No such license is listed on the [OSI site][2], though…

[1]: https://github.com/dmwm/CRABClient/blob/master/setup.py#L147
[2]: http://opensource.org/licenses/alphabetical

**Comment by annawoodard** [comment]
How about GPL or MIT?

**Comment by matz-e** [comment]
I'd more tend to [ISC](https://en.wikipedia.org/wiki/ISC_license), which is like MIT, but simpler.  GPL I'm not so fond of… I'm really wishing CMS had a proper, easy to find stand on this!

**Comment by matz-e** [comment]
For the record, [CMSSW does not have a license at all, and I don't think they are going to get one soon](https://indico.cern.ch/event/448825/session/15/contribution/46/attachments/1169561/1687838/LIcense4CMSSW.pdf).  They also mention Apache, but to me that seems like a bad idea.

**Comment by matz-e** [comment]
[Interesting read on unlicensed software (on GH).](http://250bpm.com/blog:82) [MIT](http://choosealicense.com/licenses/mit/) to resolve this?

**Comment by annawoodard** [comment]
Yes, let's go with MIT!
