### ISSUE TITLE
Efficiency plot needs to be corrected for jobs marked failed.

### ISSUE THREAD

**Issue by matz-e** [matz-e/lobster#76]
When merging, we check the availability of output files and mark jobs failed that have a non-existent output file.  These jobs still need to be subtracted from the cached efficiency plots, otherwise we over-estimate our efficiency.

**Comment by matz-e** [comment]
I'm tempted to close this, as this covers a corner-case for monitoring. From a different viewpoint, the later invalidated task did return successful at first, and should thus show up in the efficiency plot. The SE then lost the file, and is at fault? Opinions, @klannon, @annawoodard?

**Comment by klannon** [comment]
I assume this is a really rare occurrence?  If so, I wouldn't worry about it too much.

**Comment by matz-e** [comment]
It is. Currently, merge jobs would fail hard if files disappeared, and I haven't seen a single occurrence of that in the last few months. Fixing this seems more trouble than worth it, because we would be talking a handful of jobs out of 10-20k. If it were more than that ever, I think the SE needs looking into.

Now if the user randomly deletes successful files, that's a different issue, and shouldn't concern us/the monitoring.
