### ISSUE TITLE
Allow python based task configuration

### ISSUE THREAD

**Issue by matz-e** [matz-e/lobster#79]
Switching to python to generate tasks would allow us to have a more dynamic configuration of tasks, and render any scripts to generate configurations moot.  This would probably be pretty handy to have for final analysis steps (at least in my case).  Example:
```
from lobster.cmssw import Task

proto = Task(…)
toplevel = …

for sys in "cms_ttH_jes cms_ttH_qSquared".split():
    for dir in ("Up", "Down"):
        t = proto.clone()
        t.args += ['--sys', sys + dir, '--outfile', os.path.join(toplevel, sys  + dir, 'foo.root')]
```
where creating a `Task` object automatically registers it in a class-wide registry.

**Comment by annawoodard** [comment]
+1

I resisted this when you first mentioned it, but I've since come around.

**Comment by matz-e** [comment]
Just adding a stronger use case… If I want to have some more analysis studies, I have to maintain nearly identical lobster configs.  Would be nice to be able to share some of the stuff via python configs.
