### ISSUE TITLE
Dashboard improvements

### ISSUE THREAD

**Issue by khurtado** [matz-e/lobster#81]
Hello,
This update is making use of the new task_state Work Queue feature in order to (hopefully) fix our numbers.
Details are below, let me know how it goes.

Issues handled here:

1) Jobs were not reported as Aborted when terminating lobster
- We are now reading from the database and reporting all unfinished jobs as aborted. This way... even if lobster didn't terminate gracefully, we can still execute "lobster terminate" to do the job (they are already also reported as Aborted while resetting the jobits if lobster is run again too).

2) Using the new workQueue.task_state to update the job status constantly.
- We could add a threading.Timer here to make an independent thread to take care of this each i.e 5 minutes exactly, but I didn't think we need to be that strict with the time reporting interval (and didn't want to create a multithread dependence to the core process), so instead I'm checking the time while we loop over the jobs and report after (at least) 5 minutes have passed from the last dashboard reporting.
- This is however, not necessarily the interval we report to the dashboard each time for all jobs. The previous job states are recorded in a dictionary... so we only report the ones that changed in status.

**Comment by matz-e** [comment]
I think the items above have been dealt with. If not, please reopen.
