### ISSUE TITLE
We should switch to a new development style.

### ISSUE THREAD

**Issue by annawoodard** [matz-e/lobster#90]
As we’re adding developers, we should switch to the [development style](http://nvie.com/posts/a-successful-git-branching-model/) that @matz-e suggested. My preference would be that we use PRs into the dev branch for feature branches that seem like everyone might be interested in reviewing it, and skip PRs for minor things. Does anyone object to making this switch? Does anyone have an opinion on whether to rebase or leave merge commits?

**Comment by matz-e** [comment]
I would leave the merge commits.  The reasoning behind that is that it allows to track which changes belong together?

Having feature branches may make tracking changes in development a bit more cumbersome, but I think with git that is easy enough.

**Comment by annawoodard** [comment]
Hmm. Now that I tried to start using it, I'm thinking [git-flow](http://nvie.com/posts/a-successful-git-branching-model/) might be a little more complicated than we need. Unless I'm misunderstanding something, it doesn't seem to handle issue tracking very well, because issues aren't closed until the development branch is merged with the master. Maybe [this](http://scottchacon.com/2011/08/31/github-flow.html) instead?

**Comment by matz-e** [comment]
I agree.  I think the most important thing for me is to have feature branches and be able to disentangle feature commits easily.  Plus some review before changes are merged?

**Comment by klannon** [comment]
Since some of us aren't as savvy when it comes to git, would it make 
sense to have a developers README file in the repository to summarize 
the conventions you expect people to follow (along with links to the 
relevant reading)?

**Comment by matz-e** [comment]
Makes sense.  We could add the "standard" `HACKING.md` once we converge on this.

**Comment by annawoodard** [comment]
> I agree. I think the most important thing for me is to have feature branches and be able to disentangle feature commits easily. Plus some review before changes are merged?

Sounds good to me. We can probably skip the review for minor changes.

**Comment by matz-e** [comment]
Sure.  Then I think we can just push directly to the master (for the record, I think you said that too.)
