### ISSUE TITLE
Stage-out via SRM/gridftp

### ISSUE THREAD

**Issue by matz-e** [matz-e/lobster#98]
We need another stageout mode to operate without Chirp and the penalty of transferring data via WQ.

**Comment by klannon** [comment]
This would also help out the folks at CERN as they could stage output to EOS when desired.

**Comment by matz-e** [comment]
This is like the Good (tools are available), the Bad (a different subset everywhere), and the Ugly (utmost complicated setup to satisfy a few sites).

Notably:

* `srm-copy` is available, but fails due to Java complications
* `lcg-cp` is being deprecated
* `env -i gfal-copy` is official at CERN (in a clean environment, otherwise there's python ugliness)
* GFAL (python bindings) are available via the OSG CVMFS mount

To avoid unnecessary mounting of the OSG CVMFS via parrot (could be needed at CERN), I think we should stick with the deprecated `lcg-cp` and switch to `gfal-copy` whenever possible.

**Comment by matz-e** [comment]
Tested with `CMSSW_5_3_27` and `cmssw_cfg.py`.
